/-
**The exact completion of the assemblies is exact on the regular projectives.**

`Start/AsmExRegNotExact.lean` shows that the completion `ExReg(A)` of `Start/AsmExReg.lean` is
*not* exact: an internal equivalence relation need not be the kernel pair of its coequalizer.  The
obstruction is uniformity — a morphism into the relation must pick one point per point of the
source *and* compute a realizer of the chosen point from a realizer of the source point.  On a
**partitioned** base a point has exactly one realizer, so the choice can be read off it, and the
obstruction disappears.  This module proves that, on the full subcategory
`Realizability.ExReg.ExRegP` of the objects whose base is partitioned — the regular projectives of
`Asm(A)`, `Realizability.Assembly.regularProjective_iff` — **every internal equivalence relation
is the kernel pair of its quotient map**.  This is the point at which the ex/reg and the ex/lex
completions agree, and the form in which the effective topos is obtained.

The quotient is the one of `Start/AsmExRegCoeq.lean`: the base of `E` with the relation generated
by the two legs.  It is rebuilt here over the weaker data `Realizability.ExReg.EqvDataP`, which
only composes maps out of objects with a partitioned base, because that is all the full
subcategory supplies — and all that is needed, since the composable pairs can be probed by
`Realizability.ExReg.compData`.

Main definitions:

* `Realizability.ExReg.coeqObjP`, `Realizability.ExReg.coeqPreP` — the quotient of an internal
  equivalence relation of the full subcategory, and the map onto it.

Main results:

* `Realizability.ExReg.exists_liftPre` — **the lifting**: two maps out of an object with
  partitioned base which become equal in the quotient factor through the relation, uniquely up to
  homotopy;
* `Realizability.ExReg.existsUnique_lift` — the same, as the universal property of a kernel pair;
* `Realizability.ExReg.ExRegP.exists_effective_quotient` — **every internal equivalence relation
  of the completion on the projective bases is effective**: the quotient map is its coequalizer
  and the relation is that map's kernel pair;
* `Realizability.ExReg.ExRegP.isKernelPair_of_isInternalEquiv` — the kernel pair half on its own;
* `Realizability.ExReg.ExRegP.regularProjective_base`,
  `Realizability.ExReg.ExRegP.isInternalEquiv_id` — the bases of the subcategory really are
  regular projectives, and the hypothesis of the theorem is not vacuous.

What is **not** claimed: regularity of the restricted subcategory as a category in its own right
(that its finite limits and image factorizations stay inside it), its universal property among
exact categories, its topos structure, and its identification with the effective topos.
-/

import Start.AsmExRegProj

set_option relaxedAutoImplicit false
set_option autoImplicit false

universe u v

namespace Realizability

open CategoryTheory CategoryTheory.Limits

namespace ExReg

open NotExact Coeq

variable {A : Type u} [PCA A] {R E : ERel.{u, max u v} A}

/-! ### The quotient -/

/-- **The quotient of an internal equivalence relation with projective bases**: the base of `E`,
with the relation generated by the two legs. -/
noncomputable def coeqObjP {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂) : ERel.{u, max u v} A where
  base := E.base
  Prf := CoeqPrf f₁ f₂
  ends := by
    obtain ⟨pe, hpe⟩ := E.exists_sndTracker
    obtain ⟨a₁, ha₁⟩ := exists_sfThen pe
    obtain ⟨a₂, ha₂⟩ := exists_ssThen pe
    obtain ⟨t, ht⟩ := exists_pairOf a₁ a₂
    refine ⟨t, ?_⟩
    rintro w x y ⟨r, a, c₁, c₂, -, hc₁, hc₂, rfl⟩
    obtain ⟨vx, hvx, hvxr⟩ := hpe c₁ (f₁.toFun r) x hc₁
    obtain ⟨vy, hvy, hvyr⟩ := hpe c₂ (f₂.toFun r) y hc₂
    exact ⟨_, ht _ _ _ (ha₁ a c₁ c₂ vx hvx) (ha₂ a c₁ c₂ vy hvy), vx, vy, hvxr, hvyr, rfl⟩
  refl' := by
    obtain ⟨td, htd⟩ := d.diag.trackedBase
    obtain ⟨h₁, hh₁⟩ := d.diag_fst
    obtain ⟨h₂, hh₂⟩ := d.diag_snd
    obtain ⟨c, hc⟩ := exists_pairOf h₁ h₂
    obtain ⟨t, ht⟩ := exists_pairOf td c
    refine ⟨t, ?_⟩
    intro a x ha
    obtain ⟨vr, hvr, hvrr⟩ := htd a x ha
    obtain ⟨v₁, hv₁, hv₁p⟩ := hh₁ a x ha
    obtain ⟨v₂, hv₂, hv₂p⟩ := hh₂ a x ha
    exact ⟨_, ht a _ _ hvr (hc a _ _ hv₁ hv₂), d.diag.toFun x, vr, v₁, v₂, hvrr,
      hv₁p, hv₂p, rfl⟩
  symm' := by
    obtain ⟨ts, hts⟩ := d.swap.trackedBase
    obtain ⟨s₁, hs₁⟩ := d.swap_fst
    obtain ⟨s₂, hs₂⟩ := d.swap_snd
    obtain ⟨te, hte⟩ := E.trans'
    obtain ⟨ga, hga⟩ := exists_fThen ts
    obtain ⟨gb, hgb⟩ := exists_fThen s₁
    obtain ⟨gc, hgc⟩ := exists_fThen s₂
    obtain ⟨gd, hgd⟩ := exists_ssThen (PCA.i A)
    obtain ⟨ge, hge⟩ := exists_sfThen (PCA.i A)
    obtain ⟨u₁, hu₁⟩ := exists_pairApply te gb gd
    obtain ⟨u₂, hu₂⟩ := exists_pairApply te gc ge
    obtain ⟨c, hc⟩ := exists_pairOf u₁ u₂
    obtain ⟨t, ht⟩ := exists_pairOf ga c
    refine ⟨t, ?_⟩
    rintro w x y ⟨r, a, c₁, c₂, ha, hc₁, hc₂, rfl⟩
    obtain ⟨vr, hvr, hvrr⟩ := hts a r ha
    obtain ⟨v₁, hv₁, hv₁p⟩ := hs₁ a r ha
    obtain ⟨v₂, hv₂, hv₂p⟩ := hs₂ a r ha
    obtain ⟨w₁, hw₁, hw₁p⟩ := hte v₁ c₂ (f₁.toFun (d.swap.toFun r)) (f₂.toFun r) y hv₁p hc₂
    obtain ⟨w₂, hw₂, hw₂p⟩ := hte v₂ c₁ (f₂.toFun (d.swap.toFun r)) (f₁.toFun r) x hv₂p hc₁
    refine ⟨_, ht _ _ _ (hga a _ vr hvr) (hc _ _ _
      (hu₁ _ v₁ c₂ w₁ (hgb a _ v₁ hv₁) (hgd a c₁ c₂ c₂ (mem_i c₂)) hw₁)
      (hu₂ _ v₂ c₁ w₂ (hgc a _ v₂ hv₂) (hge a c₁ c₂ c₁ (mem_i c₁)) hw₂)),
      d.swap.toFun r, vr, w₁, w₂, hvrr, hw₁p, hw₂p, rfl⟩
  trans' := by
    obtain ⟨te, hte⟩ := E.trans'
    obtain ⟨se, hse⟩ := E.symm'
    obtain ⟨tk, htk⟩ := (compPtP d).trackedBase
    obtain ⟨k₁, hk₁⟩ := compPtP_fst d
    obtain ⟨k₂, hk₂⟩ := compPtP_snd d
    obtain ⟨ga, hga⟩ := exists_fThen (PCA.i A)
    obtain ⟨gc₁, hgc₁⟩ := exists_sfThen (PCA.i A)
    obtain ⟨gc₂, hgc₂⟩ := exists_ssThen (PCA.i A)
    obtain ⟨xa, hxa⟩ := exists_binLeft ga
    obtain ⟨xb, hxb⟩ := exists_binRight ga
    obtain ⟨xp, hxp⟩ := exists_binPairOf xa xb
    obtain ⟨yc, hyc⟩ := exists_binLeft gc₂
    obtain ⟨yd, hyd⟩ := exists_binRight gc₁
    obtain ⟨ye, hye⟩ := exists_binComp se yd
    obtain ⟨yp, hyp⟩ := exists_binApply te yc ye
    obtain ⟨gq, hgq⟩ := exists_binPairOf xp yp
    obtain ⟨z₀, hz₀⟩ := exists_binComp tk gq
    obtain ⟨z₁, hz₁⟩ := exists_binComp k₁ gq
    obtain ⟨z₂, hz₂⟩ := exists_binComp k₂ gq
    obtain ⟨za, hza⟩ := exists_binLeft gc₁
    obtain ⟨zb, hzb⟩ := exists_binRight gc₂
    obtain ⟨w₁, hw₁⟩ := exists_binApply te z₁ za
    obtain ⟨w₂, hw₂⟩ := exists_binApply te z₂ zb
    obtain ⟨c, hc⟩ := exists_binPairOf w₁ w₂
    obtain ⟨t, ht⟩ := exists_binPairOf z₀ c
    refine ⟨t, ?_⟩
    rintro wa wb x y z ⟨r, a, c₁, c₂, ha, hc₁, hc₂, rfl⟩ ⟨r', a', c₁', c₂', ha', hc₁', hc₂', rfl⟩
    -- the middle proof, and the composable pair it makes
    obtain ⟨sc, hsc, hscp⟩ := hse c₁' (f₁.toFun r') y hc₁'
    obtain ⟨pm, hpm, hpmp⟩ := hte c₂ sc (f₂.toFun r) y (f₁.toFun r') hc₂ hscp
    let q : CompPt f₁ f₂ := ⟨r, r', a, a', pm, ha, ha', hpmp⟩
    have hq : (pairERel (compData f₁ f₂)).base.realizes (PCA.pairEl (PCA.pairEl a a') pm) q :=
      rfl
    have hgqm : PCA.pairEl (PCA.pairEl a a') pm ∈
        (Part.some gq ⬝ Part.some (PCA.pairEl a (PCA.pairEl c₁ c₂))) ⬝
          Part.some (PCA.pairEl a' (PCA.pairEl c₁' c₂')) :=
      hgq _ _ _ _
        (hxp _ _ _ _ (hxa _ _ a (hga a _ a (mem_i a))) (hxb _ _ a' (hga a' _ a' (mem_i a'))))
        (hyp _ _ c₂ sc pm (hyc _ _ c₂ (hgc₂ a c₁ c₂ c₂ (mem_i c₂)))
          (hye _ _ c₁' sc (hyd _ _ c₁' (hgc₁ a' c₁' c₂' c₁' (mem_i c₁'))) hsc) hpm)
    obtain ⟨vr, hvr, hvrr⟩ := htk _ q hq
    obtain ⟨v₁, hv₁, hv₁p⟩ := hk₁ _ q hq
    obtain ⟨v₂, hv₂, hv₂p⟩ := hk₂ _ q hq
    obtain ⟨u₁, hu₁, hu₁p⟩ :=
      hte v₁ c₁ (f₁.toFun ((compPtP d).toFun q)) (f₁.toFun r) x hv₁p hc₁
    obtain ⟨u₂, hu₂, hu₂p⟩ :=
      hte v₂ c₂' (f₂.toFun ((compPtP d).toFun q)) (f₂.toFun r') z hv₂p hc₂'
    refine ⟨_, ht _ _ _ _ (hz₀ _ _ _ vr hgqm hvr)
      (hc _ _ _ _
        (hw₁ _ _ v₁ c₁ u₁ (hz₁ _ _ _ v₁ hgqm hv₁)
          (hza _ _ c₁ (hgc₁ a c₁ c₂ c₁ (mem_i c₁))) hu₁)
        (hw₂ _ _ v₂ c₂' u₂ (hz₂ _ _ _ v₂ hgqm hv₂)
          (hzb _ _ c₂' (hgc₂ a' c₁' c₂' c₂' (mem_i c₂'))) hu₂)),
      (compPtP d).toFun q, vr, u₁, u₂, hvrr, hu₁p, hu₂p, rfl⟩

/-- The map onto the quotient: the identity on points. -/
noncomputable def coeqPreP {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂) : Pre E (coeqObjP d) where
  toFun x := x
  tracked := by
    obtain ⟨pe, hpe⟩ := E.exists_fstTracker
    obtain ⟨td, htd⟩ := d.diag.trackedBase
    obtain ⟨h₁, hh₁⟩ := d.diag_fst
    obtain ⟨h₂, hh₂⟩ := d.diag_snd
    obtain ⟨te, hte⟩ := E.trans'
    obtain ⟨u₂, hu₂⟩ := exists_pairApply te (PCA.comp h₂ pe) (PCA.i A)
    obtain ⟨c, hc⟩ := exists_pairOf (PCA.comp h₁ pe) u₂
    obtain ⟨t, ht⟩ := exists_pairOf (PCA.comp td pe) c
    refine ⟨t, ?_⟩
    intro w x y hw
    obtain ⟨ax, hax, haxr⟩ := hpe w x y hw
    obtain ⟨vr, hvr, hvrr⟩ := htd ax x haxr
    obtain ⟨v₁, hv₁, hv₁p⟩ := hh₁ ax x haxr
    obtain ⟨v₂, hv₂, hv₂p⟩ := hh₂ ax x haxr
    obtain ⟨v₃, hv₃, hv₃p⟩ := hte v₂ w (f₂.toFun (d.diag.toFun x)) x y hv₂p hw
    exact ⟨_, ht w _ _ (mem_comp hax hvr)
      (hc w _ _ (mem_comp hax hv₁) (hu₂ w v₂ w v₃ (mem_comp hax hv₂) (mem_i w) hv₃)),
      d.diag.toFun x, vr, v₁, v₃, hvrr, hv₁p, hv₃p, rfl⟩

/-- The two legs become homotopic after the quotient map. -/
theorem coeq_homotopicP {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂) :
    Homotopic (f₁.comp (coeqPreP d)) (f₂.comp (coeqPreP d)) := by
  obtain ⟨re, hre⟩ := E.refl'
  obtain ⟨t₁, ht₁⟩ := f₁.trackedBase
  obtain ⟨t₂, ht₂⟩ := f₂.trackedBase
  obtain ⟨c, hc⟩ := exists_pairOf (PCA.comp re t₁) (PCA.comp re t₂)
  obtain ⟨t, ht⟩ := exists_pairOf (PCA.i A) c
  refine ⟨t, ?_⟩
  intro a r ha
  obtain ⟨x₁, hx₁, hx₁r⟩ := ht₁ a r ha
  obtain ⟨x₂, hx₂, hx₂r⟩ := ht₂ a r ha
  obtain ⟨p₁, hp₁, hp₁p⟩ := hre x₁ (f₁.toFun r) hx₁r
  obtain ⟨p₂, hp₂, hp₂p⟩ := hre x₂ (f₂.toFun r) hx₂r
  exact ⟨_, ht a a _ (mem_i a) (hc a _ _ (mem_comp hx₁ hp₁) (mem_comp hx₂ hp₂)),
    r, a, p₁, p₂, ha, hp₁p, hp₂p, rfl⟩


/-! ### The lifting -/

/-- **The lifting.**  Two maps out of an object with a partitioned base which become homotopic in
the quotient factor through the relation.  This is the step that fails for a general base: the
factor has to pick a point of `R` over each point of the source *and* compute a realizer of it,
and it is the uniqueness of the realizer of a point of a partitioned assembly that makes the
choice uniform. -/
theorem exists_liftPre {T : ERel.{u, max u v} A} {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂)
    (hjm : JMTracker f₁ f₂) (hT : Assembly.Partitioned T.base) (u w : Pre T E)
    (h : Homotopic (u.comp (coeqPreP d)) (w.comp (coeqPreP d))) :
    ∃ k : Pre T R, Homotopic (k.comp f₁) u ∧ Homotopic (k.comp f₂) w := by
  classical
  obtain ⟨e, he⟩ := hT
  obtain ⟨hh, hhh⟩ := h
  obtain ⟨tj, htj⟩ := hjm
  have key : ∀ t : T.base.carrier, ∃ (r : R.base.carrier) (a c₁ c₂ : A),
      R.base.realizes a r ∧ E.Prf c₁ (f₁.toFun r) (u.toFun t) ∧
        E.Prf c₂ (f₂.toFun r) (w.toFun t) ∧
        PCA.pairEl a (PCA.pairEl c₁ c₂) ∈ PCA.app hh (e t) := by
    intro t
    obtain ⟨z, hz, r, a, c₁, c₂, ha, hc₁, hc₂, hzeq⟩ := hhh (e t) t ((he (e t) t).2 rfl)
    exact ⟨r, a, c₁, c₂, ha, hc₁, hc₂, hzeq ▸ hz⟩
  choose rr ra rc₁ rc₂ hra hrc₁ hrc₂ hmem using key
  -- the three components of the answer of the homotopy, as unary combinators
  have hfst : ∀ t : T.base.carrier, ra t ∈ PCA.app (PCA.comp (PCA.fstComb A) hh) (e t) :=
    fun t => mem_comp (hmem t) (mem_fstComb _ _)
  have hsnd₁ : ∀ t : T.base.carrier,
      rc₁ t ∈ PCA.app (PCA.comp (PCA.comp (PCA.fstComb A) (PCA.sndComb A)) hh) (e t) :=
    fun t => mem_comp (hmem t) (mem_comp (mem_sndComb _ _) (mem_fstComb _ _))
  have hsnd₂ : ∀ t : T.base.carrier,
      rc₂ t ∈ PCA.app (PCA.comp (PCA.comp (PCA.sndComb A) (PCA.sndComb A)) hh) (e t) :=
    fun t => mem_comp (hmem t) (mem_comp (mem_sndComb _ _) (mem_sndComb _ _))
  refine ⟨⟨rr, ?_⟩,
    ⟨PCA.comp (PCA.comp (PCA.fstComb A) (PCA.sndComb A)) hh, fun a t ha => ⟨rc₁ t, ?_, hrc₁ t⟩⟩,
    ⟨PCA.comp (PCA.comp (PCA.sndComb A) (PCA.sndComb A)) hh, fun a t ha => ⟨rc₂ t, ?_, hrc₂ t⟩⟩⟩
  · -- the tracker of the lift
    obtain ⟨pf, hpf⟩ := T.exists_fstTracker
    obtain ⟨ps, hps⟩ := T.exists_sndTracker
    obtain ⟨cu, hcu⟩ := u.tracked
    obtain ⟨cw, hcw⟩ := w.tracked
    obtain ⟨se, hse⟩ := E.symm'
    obtain ⟨te, hte⟩ := E.trans'
    -- the data at the two endpoints
    set ga : A := PCA.comp (PCA.comp (PCA.fstComb A) hh) pf with hga
    set ga' : A := PCA.comp (PCA.comp (PCA.fstComb A) hh) ps with hga'
    set gc₁ : A := PCA.comp (PCA.comp (PCA.comp (PCA.fstComb A) (PCA.sndComb A)) hh) pf
      with hgc₁
    set gc₁' : A := PCA.comp (PCA.comp (PCA.comp (PCA.fstComb A) (PCA.sndComb A)) hh) ps
      with hgc₁'
    set gc₂ : A := PCA.comp (PCA.comp (PCA.comp (PCA.sndComb A) (PCA.sndComb A)) hh) pf
      with hgc₂
    set gc₂' : A := PCA.comp (PCA.comp (PCA.comp (PCA.sndComb A) (PCA.sndComb A)) hh) ps
      with hgc₂'
    obtain ⟨m₁, hm₁⟩ := exists_pairApply te gc₁ cu
    obtain ⟨q₁, hq₁⟩ := exists_pairApply te m₁ (PCA.comp se gc₁')
    obtain ⟨m₂, hm₂⟩ := exists_pairApply te gc₂ cw
    obtain ⟨q₂, hq₂⟩ := exists_pairApply te m₂ (PCA.comp se gc₂')
    obtain ⟨pa, hpa⟩ := exists_pairOf ga ga'
    obtain ⟨pq, hpq⟩ := exists_pairOf q₁ q₂
    obtain ⟨pp, hpp⟩ := exists_pairOf pa pq
    refine ⟨PCA.comp tj pp, ?_⟩
    intro s t t' hs
    -- the realizers of the two endpoints, which are the chosen ones
    obtain ⟨vt, hvt, hvtr⟩ := hpf s t t' hs
    obtain ⟨vt', hvt', hvt'r⟩ := hps s t t' hs
    have hvte : vt = e t := (he vt t).1 hvtr
    have hvt'e : vt' = e t' := (he vt' t').1 hvt'r
    subst hvte
    subst hvt'e
    -- the two proofs in `E`
    obtain ⟨p₁, hp₁, hp₁p⟩ := hcu s t t' hs
    obtain ⟨p₂, hp₂, hp₂p⟩ := hcw s t t' hs
    obtain ⟨sc₁, hsc₁, hsc₁p⟩ := hse (rc₁ t') (f₁.toFun (rr t')) (u.toFun t') (hrc₁ t')
    obtain ⟨sc₂, hsc₂, hsc₂p⟩ := hse (rc₂ t') (f₂.toFun (rr t')) (w.toFun t') (hrc₂ t')
    obtain ⟨y₁, hy₁, hy₁p⟩ := hte (rc₁ t) p₁ (f₁.toFun (rr t)) (u.toFun t) (u.toFun t')
      (hrc₁ t) hp₁p
    obtain ⟨z₁, hz₁, hz₁p⟩ := hte y₁ sc₁ (f₁.toFun (rr t)) (u.toFun t') (f₁.toFun (rr t'))
      hy₁p hsc₁p
    obtain ⟨y₂, hy₂, hy₂p⟩ := hte (rc₂ t) p₂ (f₂.toFun (rr t)) (w.toFun t) (w.toFun t')
      (hrc₂ t) hp₂p
    obtain ⟨z₂, hz₂, hz₂p⟩ := hte y₂ sc₂ (f₂.toFun (rr t)) (w.toFun t') (f₂.toFun (rr t'))
      hy₂p hsc₂p
    -- and the joint monicity tracker
    obtain ⟨vr, hvr, hvrp⟩ := htj (rr t) (rr t') (ra t) (ra t') z₁ z₂ (hra t) (hra t')
      hz₁p hz₂p
    have hmemA : ra t ∈ PCA.app ga s := by
      rw [hga]; exact mem_comp hvt (hfst t)
    have hmemA' : ra t' ∈ PCA.app ga' s := by
      rw [hga']; exact mem_comp hvt' (hfst t')
    have hmemC₁ : rc₁ t ∈ PCA.app gc₁ s := by
      rw [hgc₁]; exact mem_comp hvt (hsnd₁ t)
    have hmemC₁' : rc₁ t' ∈ PCA.app gc₁' s := by
      rw [hgc₁']; exact mem_comp hvt' (hsnd₁ t')
    have hmemC₂ : rc₂ t ∈ PCA.app gc₂ s := by
      rw [hgc₂]; exact mem_comp hvt (hsnd₂ t)
    have hmemC₂' : rc₂ t' ∈ PCA.app gc₂' s := by
      rw [hgc₂']; exact mem_comp hvt' (hsnd₂ t')
    refine ⟨vr, mem_comp (hpp s _ _ (hpa s _ _ hmemA hmemA')
      (hpq s _ _
        (hq₁ s y₁ sc₁ z₁ (hm₁ s (rc₁ t) p₁ y₁ hmemC₁ hp₁ hy₁) (mem_comp hmemC₁' hsc₁) hz₁)
        (hq₂ s y₂ sc₂ z₂ (hm₂ s (rc₂ t) p₂ y₂ hmemC₂ hp₂ hy₂) (mem_comp hmemC₂' hsc₂) hz₂)))
      hvr, hvrp⟩
  · have hae : a = e t := (he a t).1 ha
    subst hae
    exact hsnd₁ t
  · have hae : a = e t := (he a t).1 ha
    subst hae
    exact hsnd₂ t

/-- Two maps into `R` with homotopic composites with the two legs are homotopic: this is joint
monicity, read on realizers. -/
theorem homotopic_of_jmTracker {T : ERel.{u, max u v} A} {f₁ f₂ : Pre R E}
    (hjm : JMTracker f₁ f₂) (g k : Pre T R)
    (h₁ : Homotopic (g.comp f₁) (k.comp f₁)) (h₂ : Homotopic (g.comp f₂) (k.comp f₂)) :
    Homotopic g k := by
  obtain ⟨tj, htj⟩ := hjm
  obtain ⟨t₁, ht₁⟩ := h₁
  obtain ⟨t₂, ht₂⟩ := h₂
  obtain ⟨bg, hbg⟩ := g.trackedBase
  obtain ⟨bk, hbk⟩ := k.trackedBase
  obtain ⟨pa, hpa⟩ := exists_pairOf bg bk
  obtain ⟨pq, hpq⟩ := exists_pairOf t₁ t₂
  obtain ⟨pp, hpp⟩ := exists_pairOf pa pq
  refine ⟨PCA.comp tj pp, fun a t ha => ?_⟩
  obtain ⟨ag, hag, hagr⟩ := hbg a t ha
  obtain ⟨ak, hak, hakr⟩ := hbk a t ha
  obtain ⟨p₁, hp₁, hp₁p⟩ := ht₁ a t ha
  obtain ⟨p₂, hp₂, hp₂p⟩ := ht₂ a t ha
  obtain ⟨vr, hvr, hvrp⟩ :=
    htj (g.toFun t) (k.toFun t) ag ak p₁ p₂ hagr hakr hp₁p hp₂p
  exact ⟨vr, mem_comp (hpp a _ _ (hpa a _ _ hag hak) (hpq a _ _ hp₁ hp₂)) hvr, hvrp⟩

/-- **The universal property of the relation as a kernel pair**, read on pre-morphisms: a pair of
maps out of an object with partitioned base which agree in the quotient factors uniquely through
the relation. -/
theorem existsUnique_lift {T : ERel.{u, max u v} A} {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂)
    (hjm : JMTracker f₁ f₂) (hT : Assembly.Partitioned T.base) (u w : Pre T E)
    (h : homOf u ≫ homOf (coeqPreP d) = homOf w ≫ homOf (coeqPreP d)) :
    ∃! m : T ⟶ R, m ≫ homOf f₁ = homOf u ∧ m ≫ homOf f₂ = homOf w := by
  obtain ⟨k, hk₁, hk₂⟩ := exists_liftPre d hjm hT u w
    (homOf_eq_iff.1 (by rw [← homOf_comp, ← homOf_comp]; exact h))
  refine ⟨homOf k, ⟨by rw [homOf_comp]; exact homOf_eq_iff.2 hk₁,
    by rw [homOf_comp]; exact homOf_eq_iff.2 hk₂⟩, ?_⟩
  rintro m ⟨hm₁, hm₂⟩
  obtain ⟨g, rfl⟩ := homOf_surjective m
  rw [homOf_comp] at hm₁ hm₂
  refine homOf_eq_iff.2 (homotopic_of_jmTracker hjm g k ?_ ?_)
  · exact (homOf_eq_iff.1 hm₁).trans hk₁.symm
  · exact (homOf_eq_iff.1 hm₂).trans hk₂.symm

/-! ### The universal property of the quotient -/

/-- A map out of `E` which identifies the two legs descends to the quotient. -/
noncomputable def descPreP {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂) {Z : ERel.{u, max u v} A}
    (G : Pre E Z)
    (hG : Homotopic (f₁.comp G) (f₂.comp G)) : Pre (coeqObjP d) Z where
  toFun := G.toFun
  tracked := by
    obtain ⟨tg, htg⟩ := G.tracked
    obtain ⟨sz, hsz⟩ := Z.symm'
    obtain ⟨tz, htz⟩ := Z.trans'
    obtain ⟨hg, hhg⟩ := hG
    obtain ⟨ga, hga⟩ := exists_fThen (PCA.i A)
    obtain ⟨gc₁, hgc₁⟩ := exists_sfThen (PCA.i A)
    obtain ⟨gc₂, hgc₂⟩ := exists_ssThen (PCA.i A)
    obtain ⟨e₁, he₁⟩ := exists_pairApply tz (PCA.comp sz (PCA.comp tg gc₁))
      (PCA.comp hg ga)
    obtain ⟨t, ht⟩ := exists_pairApply tz e₁ (PCA.comp tg gc₂)
    refine ⟨t, ?_⟩
    rintro w x y ⟨r, a, c₁, c₂, ha, hc₁, hc₂, rfl⟩
    obtain ⟨z₁, hz₁, hz₁p⟩ := htg c₁ (f₁.toFun r) x hc₁
    obtain ⟨z₁', hz₁', hz₁'p⟩ := hsz z₁ (G.toFun (f₁.toFun r)) (G.toFun x) hz₁p
    obtain ⟨z₂, hz₂, hz₂p⟩ := hhg a r ha
    obtain ⟨z₃, hz₃, hz₃p⟩ := htg c₂ (f₂.toFun r) y hc₂
    obtain ⟨y₁, hy₁, hy₁p⟩ :=
      htz z₁' z₂ (G.toFun x) (G.toFun (f₁.toFun r)) (G.toFun (f₂.toFun r)) hz₁'p hz₂p
    obtain ⟨y₂, hy₂, hy₂p⟩ :=
      htz y₁ z₃ (G.toFun x) (G.toFun (f₂.toFun r)) (G.toFun y) hy₁p hz₃p
    refine ⟨y₂, ht _ y₁ z₃ y₂
      (he₁ _ z₁' z₂ y₁
        (mem_comp (mem_comp (hgc₁ a c₁ c₂ c₁ (mem_i c₁)) hz₁) hz₁')
        (mem_comp (hga a _ a (mem_i a)) hz₂) hy₁)
      (mem_comp (hgc₂ a c₁ c₂ c₂ (mem_i c₂)) hz₃) hy₂, hy₂p⟩

theorem coeq_comp_descPreP {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂) {Z : ERel.{u, max u v} A}
    (G : Pre E Z) (hG : Homotopic (f₁.comp G) (f₂.comp G)) :
    (coeqPreP d).comp (descPreP d G hG) = G := Pre.ext rfl

/-- The quotient map is an epimorphism: the quotient has the same base, with the same
realizers. -/
instance epi_coeqPrePP {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂) : Epi (homOf (coeqPreP d)) where
  left_cancellation {W} g h hgh := by
    obtain ⟨G, rfl⟩ := homOf_surjective g
    obtain ⟨H, rfl⟩ := homOf_surjective h
    rw [homOf_comp, homOf_comp, homOf_eq_iff] at hgh
    obtain ⟨t, ht⟩ := hgh
    exact homOf_eq_iff.2 ⟨t, fun a x ha => ht a x ha⟩

/-- The cofork given by the quotient map. -/
noncomputable def coeqCoforkP {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂) :
    Cofork (homOf f₁) (homOf f₂) :=
  Cofork.ofπ (homOf (coeqPreP d)) (by
    rw [homOf_comp, homOf_comp]
    exact homOf_eq_iff.2 (coeq_homotopicP d))

@[simp] theorem coeqCoforkP_π {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂) :
    Cofork.π (coeqCoforkP d) = homOf (coeqPreP d) := rfl

/-- The condition of a cofork, read on a representative of its leg. -/
theorem homotopic_of_coforkP {f₁ f₂ : Pre R E} (s : Cofork (homOf f₁) (homOf f₂)) :
    Homotopic (f₁.comp (rep (Cofork.π s))) (f₂.comp (rep (Cofork.π s))) := by
  refine homOf_eq_iff.1 ?_
  rw [← homOf_comp, ← homOf_comp, homOf_rep]
  exact s.condition

/-- **The quotient is the coequalizer of the two legs.** -/
noncomputable def coeqCoforkPIsColimit {f₁ f₂ : Pre R E} (d : EqvDataP f₁ f₂) :
    IsColimit (coeqCoforkP d) :=
  Cofork.IsColimit.mk _
    (fun s => homOf (descPreP d (rep (Cofork.π s)) (homotopic_of_coforkP s)))
    (fun s => by
      have h : homOf ((coeqPreP d).comp
          (descPreP d (rep (Cofork.π s)) (homotopic_of_coforkP s)))
          = homOf (rep (Cofork.π s)) := congrArg homOf (coeq_comp_descPreP _ _ _)
      rw [homOf_rep] at h
      exact h)
    (fun s m hm => by
      have h : homOf ((coeqPreP d).comp
          (descPreP d (rep (Cofork.π s)) (homotopic_of_coforkP s)))
          = homOf (rep (Cofork.π s)) := congrArg homOf (coeq_comp_descPreP _ _ _)
      rw [homOf_rep] at h
      have hfac : Cofork.π (coeqCoforkP d) ≫
          homOf (descPreP d (rep (Cofork.π s)) (homotopic_of_coforkP s)) = Cofork.π s := h
      exact (cancel_epi (homOf (coeqPreP d))).1 (hm.trans hfac.symm))


/-! ### Effectiveness on the projective bases -/

namespace ExRegP

variable {Rp Ep : ExRegP.{u, max u v} A}

/-- Morphisms of the full subcategory are determined by the morphisms of the completion they
carry. -/
theorem hom_ext {X Y : ExRegP.{u, max u v} A} {a b : X ⟶ Y} (h : a.hom = b.hom) : a = b :=
  (ProjBase.{u, max u v} A).ι.map_injective h

/-- **Every internal equivalence relation of the completion on the projective bases is
effective**: the quotient map onto the object with the same base and the relation that the two
legs generate is their coequalizer, and they are its kernel pair.  Over a general base this fails
— `Realizability.ExReg.NotExact.exists_internalEquiv_not_kernelPair`. -/
theorem exists_effective_quotient (p₁ p₂ : Rp ⟶ Ep)
    (h : NotExact.IsInternalEquiv p₁ p₂) :
    ∃ (Q : ExRegP.{u, max u v} A) (q : Ep ⟶ Q) (hq : p₁ ≫ q = p₂ ≫ q),
      IsKernelPair q p₁ p₂ ∧ Nonempty (IsColimit (Cofork.ofπ q hq)) := by
  classical
  obtain ⟨f₁, hf₁⟩ := homOf_surjective p₁.hom
  obtain ⟨f₂, hf₂⟩ := homOf_surjective p₂.hom
  -- joint monicity, read on realizers
  have hjm : JMTracker f₁ f₂ := by
    refine jmTracker_of_jointlyMono f₁ f₂ fun T hT g k hg hk => ?_
    have hgk := h.jointly_mono (T := ⟨T, hT⟩) (ObjectProperty.homMk g) (ObjectProperty.homMk k)
      (hom_ext (by simpa only [ObjectProperty.FullSubcategory.comp_hom,
        ObjectProperty.homMk_hom, ← hf₁] using hg))
      (hom_ext (by simpa only [ObjectProperty.FullSubcategory.comp_hom,
        ObjectProperty.homMk_hom, ← hf₂] using hk))
    exact congrArg (fun m => InducedCategory.Hom.hom m) hgk
  -- the data of the equivalence relation
  obtain ⟨d⟩ : Nonempty (EqvDataP f₁ f₂) := by
    refine eqvDataP_of_isInternalEquiv f₁ f₂ ?_ ?_ ?_
    · obtain ⟨dd, hd₁, hd₂⟩ := h.refl'
      refine ⟨dd.hom, ?_, ?_⟩
      · rw [hf₁]
        exact congrArg (fun m => InducedCategory.Hom.hom m) hd₁
      · rw [hf₂]
        exact congrArg (fun m => InducedCategory.Hom.hom m) hd₂
    · obtain ⟨ss, hs₁, hs₂⟩ := h.symm'
      refine ⟨ss.hom, ?_, ?_⟩
      · rw [hf₁, hf₂]
        exact congrArg (fun m => InducedCategory.Hom.hom m) hs₁
      · rw [hf₁, hf₂]
        exact congrArg (fun m => InducedCategory.Hom.hom m) hs₂
    · intro T hT g k hgk
      obtain ⟨m, hm₁, hm₂⟩ := h.trans' (T := ⟨T, hT⟩)
        (ObjectProperty.homMk g) (ObjectProperty.homMk k)
        (hom_ext (by simpa only [ObjectProperty.FullSubcategory.comp_hom,
          ObjectProperty.homMk_hom, ← hf₁, ← hf₂] using hgk))
      refine ⟨m.hom, ?_, ?_⟩
      · rw [hf₁]
        exact congrArg (fun m => InducedCategory.Hom.hom m) hm₁
      · rw [hf₂]
        exact congrArg (fun m => InducedCategory.Hom.hom m) hm₂
  -- the quotient, which has the same base as `E`, hence is again an object of the subcategory
  have hcomm : p₁ ≫ ObjectProperty.homMk (Y := ⟨coeqObjP d, Ep.property⟩) (homOf (coeqPreP d)) =
      p₂ ≫ ObjectProperty.homMk (Y := ⟨coeqObjP d, Ep.property⟩) (homOf (coeqPreP d)) := by
    refine hom_ext ?_
    simp only [ObjectProperty.FullSubcategory.comp_hom, ObjectProperty.homMk_hom, ← hf₁, ← hf₂,
      homOf_comp]
    exact homOf_eq_iff.2 (coeq_homotopicP d)
  -- the universal property, which is the lifting
  have hlift : ∀ s : PullbackCone
      (ObjectProperty.homMk (Y := ⟨coeqObjP d, Ep.property⟩) (homOf (coeqPreP d)))
      (ObjectProperty.homMk (Y := ⟨coeqObjP d, Ep.property⟩) (homOf (coeqPreP d))),
      ∃! m : s.pt.obj ⟶ Rp.obj,
        m ≫ homOf f₁ = homOf (rep s.fst.hom) ∧ m ≫ homOf f₂ = homOf (rep s.snd.hom) := by
    intro s
    refine existsUnique_lift d hjm s.pt.property _ _ ?_
    rw [homOf_rep, homOf_rep]
    exact congrArg (fun m => InducedCategory.Hom.hom m) s.condition
  -- the descent condition of a cofork, read on a representative
  have hcond : ∀ s : Cofork p₁ p₂,
      Homotopic (f₁.comp (rep (Cofork.π s).hom)) (f₂.comp (rep (Cofork.π s).hom)) := by
    intro s
    refine homOf_eq_iff.1 ?_
    rw [← homOf_comp, ← homOf_comp, homOf_rep, hf₁, hf₂]
    exact congrArg (fun m => InducedCategory.Hom.hom m) s.condition
  refine ⟨⟨coeqObjP d, Ep.property⟩, ObjectProperty.homMk (homOf (coeqPreP d)), hcomm, ?_, ⟨?_⟩⟩
  · refine IsPullback.of_isLimit (PullbackCone.IsLimit.mk hcomm
      (fun s => ObjectProperty.homMk (hlift s).choose) (fun s => ?_) (fun s => ?_)
      (fun s m hm₁ hm₂ => ?_))
    · refine hom_ext ?_
      simp only [ObjectProperty.FullSubcategory.comp_hom, ObjectProperty.homMk_hom, ← hf₁]
      rw [(hlift s).choose_spec.1.1, homOf_rep]
    · refine hom_ext ?_
      simp only [ObjectProperty.FullSubcategory.comp_hom, ObjectProperty.homMk_hom, ← hf₂]
      rw [(hlift s).choose_spec.1.2, homOf_rep]
    · refine hom_ext ?_
      refine (hlift s).choose_spec.2 m.hom ⟨?_, ?_⟩
      · rw [homOf_rep, hf₁]
        exact congrArg (fun m => InducedCategory.Hom.hom m) hm₁
      · rw [homOf_rep, hf₂]
        exact congrArg (fun m => InducedCategory.Hom.hom m) hm₂
  · -- and the quotient map is the coequalizer
    refine Cofork.IsColimit.mk _
      (fun s => ObjectProperty.homMk (homOf (descPreP d (rep (Cofork.π s).hom) (hcond s))))
      (fun s => ?_) (fun s m hm => ?_)
    · refine hom_ext ?_
      simp only [Cofork.π_ofπ, ObjectProperty.FullSubcategory.comp_hom,
        ObjectProperty.homMk_hom, homOf_comp]
      rw [coeq_comp_descPreP, homOf_rep]
    · refine hom_ext ?_
      refine (cancel_epi (homOf (coeqPreP d))).1 ?_
      have hm' := congrArg (fun m => InducedCategory.Hom.hom m) hm
      simp only [Cofork.π_ofπ, ObjectProperty.FullSubcategory.comp_hom,
        ObjectProperty.homMk_hom] at hm' ⊢
      rw [hm', homOf_comp, coeq_comp_descPreP, homOf_rep]

/-- **The completion restricted to the projective bases is effective**: every internal
equivalence relation in it is the kernel pair of a morphism.  This is the corrected form of the
exactness that fails for the completion on all assemblies. -/
theorem isKernelPair_of_isInternalEquiv (p₁ p₂ : Rp ⟶ Ep)
    (h : NotExact.IsInternalEquiv p₁ p₂) :
    ∃ (Q : ExRegP.{u, max u v} A) (q : Ep ⟶ Q), IsKernelPair q p₁ p₂ := by
  obtain ⟨Q, q, -, hker, -⟩ := exists_effective_quotient p₁ p₂ h
  exact ⟨Q, q, hker⟩

/-! ### The subcategory is the one on the regular projectives, and is not empty -/

/-- **The objects of the subcategory are exactly those whose base is a regular projective** of
`Asm(A)`: a partitioned assembly is regular projective
(`Realizability.Assembly.regularProjective_iff`). -/
theorem regularProjective_base (X : ExRegP.{u, max u v} A) :
    Assembly.RegularProjective X.obj.base :=
  Assembly.Partitioned.regularProjective X.property

/-- An assembly with one realizer per point, with equality, is an object of the subcategory. -/
def embP (X : Assembly.{u, max u v} A) (hX : Assembly.Partitioned X) : ExRegP.{u, max u v} A :=
  ⟨eqERel X, hX⟩

/-- The diagonal of any object is an internal equivalence relation, so the hypothesis of
`Realizability.ExReg.ExRegP.exists_effective_quotient` is not vacuous. -/
theorem isInternalEquiv_id (X : ExRegP.{u, max u v} A) :
    NotExact.IsInternalEquiv (𝟙 X) (𝟙 X) where
  jointly_mono f g h₁ _ := by simpa using h₁
  refl' := ⟨𝟙 X, by simp, by simp⟩
  symm' := ⟨𝟙 X, rfl, rfl⟩
  trans' f g hfg := ⟨f, rfl, by simpa using hfg⟩

end ExRegP

end ExReg

end Realizability
