/-
# Martin-Löf randomness

This file adds the measure-theoretic layer of algorithmic randomness on top of the algorithmic
information theory developed in `Start/Kraft.lean`, `Start/ChaitinOmega.lean` and
`Start/OmegaIncompressible.lean`.

* `Lambda.cantorMeasure` — the fair-coin (uniform) probability measure on Cantor space
  `ℕ → Bool`, obtained from Mathlib's infinite product measure, with
  `Lambda.cantorMeasure_cylinder : cantorMeasure (cylinder σ) = 2⁻¹ ^ σ.length`.
* `Lambda.MLTest` — a *Martin-Löf test*: a uniformly `Σ⁰₁` sequence of open subsets of Cantor
  space whose `c`-th member has measure at most `2 ^ (-c)`.  Effectiveness is carried by a
  computable "enters by stage `j`" matrix, which is the usual normal form of a `Σ⁰₁` class.
* `Lambda.MLRandom X` — `X` passes every Martin-Löf test.

Two theorems are proved about the notion.

* `Lambda.not_mlRandom_of_computable` — no computable sequence is Martin-Löf random.  This is
  what makes the definition non-vacuous in the right direction: the tests really do capture
  regularities.
* `Lambda.exists_const_le_kolmP_prefix_of_mlRandom` — **the easy half of the Levin–Schnorr
  theorem**: if `X` is Martin-Löf random then its prefixes are incompressible for the prefix
  complexity `Lambda.kolmP` of the binary lambda-calculus machine,
  `∃ c, ∀ n, n ≤ kolmP ⌜X ↾ n⌝ + c`.  The proof is the standard one: the strings that are
  compressible by `c` bits generate an open set of measure at most `2 ^ (-c)`, by Kraft's
  inequality `Lambda.kraft_kolmP`, and that family is a Martin-Löf test.

## What is *not* proved here

The converse half of Levin–Schnorr — incompressibility implies Martin-Löf randomness — is **not**
proved, and it is not available for this machine.  It rests on the Kraft–Chaitin machine
existence theorem applied to an *additively optimal* prefix machine, and the machine underlying
`Lambda.kolmP` (closed lambda terms under the self-delimiting code `Lambda.bits`, with no input
stream) is not additively optimal: writing `ℓ` arbitrary payload bits into a lambda term costs
strictly more than `ℓ + O(1)` bits.  Consequently
`Lambda.exists_const_le_kolmP_omegaPrefix` (Chaitin incompressibility for `Ω`, proved in
`Start/OmegaIncompressible.lean`) does **not** yield `MLRandom` for the bit sequence of `Ω`, and
the Martin-Löf randomness of this project's `Ω` remains open here.
-/

import Start.OmegaIncompressible
import Mathlib.Probability.ProductMeasure

set_option relaxedAutoImplicit false
set_option autoImplicit false

namespace Lambda

open MeasureTheory

noncomputable section

------------------------------------------------------------------------
-- The uniform measure on Cantor space
------------------------------------------------------------------------

/-- The fair coin on `Bool`. -/
def coinMeasure : Measure Bool := (PMF.uniformOfFintype Bool).toMeasure

instance : IsProbabilityMeasure coinMeasure := by
  unfold coinMeasure; infer_instance

@[simp] theorem coinMeasure_singleton (b : Bool) : coinMeasure {b} = 2⁻¹ := by
  simp [coinMeasure, PMF.uniformOfFintype_apply]

/-- The uniform (fair coin) probability measure on Cantor space `ℕ → Bool`. -/
def cantorMeasure : Measure (ℕ → Bool) := Measure.infinitePi fun _ : ℕ => coinMeasure

/-- The basic clopen set of all sequences extending the finite string `σ`. -/
def cylinder (σ : List Bool) : Set (ℕ → Bool) := {X | ∀ i, (h : i < σ.length) → X i = σ[i]}

theorem cylinder_eq_pi (σ : List Bool) :
    cylinder σ = (↑(Finset.range σ.length) : Set ℕ).pi fun i => {σ.getD i Bool.false} := by
  ext X
  simp only [cylinder, Set.mem_pi, Set.mem_setOf_eq, Finset.coe_range, Set.mem_Iio,
    Set.mem_singleton_iff]
  exact ⟨fun h i hi => by simp [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem hi, h i hi],
    fun h i hi => by simpa [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem hi] using h i hi⟩

/-- **The measure of a cylinder is `2 ^ (-|σ|)`.** -/
theorem cantorMeasure_cylinder (σ : List Bool) :
    cantorMeasure (cylinder σ) = (2 : ENNReal)⁻¹ ^ σ.length := by
  rw [cylinder_eq_pi, cantorMeasure,
    Measure.infinitePi_pi _ fun _ _ => MeasurableSet.singleton _]
  simp

theorem cylinder_mono {σ τ : List Bool} (h : σ <+: τ) : cylinder τ ⊆ cylinder σ := by
  obtain ⟨u, rfl⟩ := h
  intro X hX i hi
  have hi' : i < (σ ++ u).length := by simp; omega
  have := hX i hi'
  rwa [List.getElem_append_left hi] at this

theorem measurableSet_cylinder (σ : List Bool) : MeasurableSet (cylinder σ) := by
  rw [cylinder_eq_pi]
  exact MeasurableSet.pi (Finset.range σ.length).countable_toSet
    fun i _ => MeasurableSet.singleton _

------------------------------------------------------------------------
-- Open subsets of Cantor space generated by sets of strings
------------------------------------------------------------------------

/-- The open set generated by a set of finite strings. -/
def openOf (W : Set (List Bool)) : Set (ℕ → Bool) := ⋃ σ ∈ W, cylinder σ

theorem mem_openOf {W : Set (List Bool)} {X : ℕ → Bool} :
    X ∈ openOf W ↔ ∃ σ ∈ W, X ∈ cylinder σ := by
  simp [openOf]

theorem cantorMeasure_openOf_le (W : Set (List Bool)) :
    cantorMeasure (openOf W) ≤ ∑' σ : W, (2 : ENNReal)⁻¹ ^ (σ : List Bool).length := by
  refine le_trans (measure_biUnion_le _ W.to_countable _) ?_
  exact le_of_eq (tsum_congr fun σ => cantorMeasure_cylinder _)

------------------------------------------------------------------------
-- Martin-Löf tests
------------------------------------------------------------------------

/-- A **Martin-Löf test**: a uniformly `Σ⁰₁` sequence of open subsets of Cantor space, the `c`-th
of which has measure at most `2 ^ (-c)`.

The `Σ⁰₁` data is given in the usual normal form: a computable matrix `enter c σ j`, read as
"the string `σ` has entered the `c`-th set by stage `j`". -/
structure MLTest where
  /-- `enter c σ j = true` means that `σ` has entered the `c`-th open set by stage `j`. -/
  enter : ℕ → List Bool → ℕ → Bool
  /-- The matrix is computable, so each level is a `Σ⁰₁` class, uniformly in `c`. -/
  enter_computable : Computable fun p : ℕ × List Bool × ℕ => enter p.1 p.2.1 p.2.2
  /-- The `c`-th level has measure at most `2 ^ (-c)`. -/
  measure_le : ∀ c : ℕ,
    cantorMeasure (openOf {σ | ∃ j, enter c σ j = Bool.true}) ≤ (2 : ENNReal)⁻¹ ^ c

/-- The set of strings enumerated at level `c` of a Martin-Löf test. -/
def MLTest.strings (T : MLTest) (c : ℕ) : Set (List Bool) :=
  {σ | ∃ j, T.enter c σ j = Bool.true}

/-- The `c`-th open set of a Martin-Löf test. -/
def MLTest.level (T : MLTest) (c : ℕ) : Set (ℕ → Bool) := openOf (T.strings c)

theorem MLTest.measure_level_le (T : MLTest) (c : ℕ) :
    cantorMeasure (T.level c) ≤ (2 : ENNReal)⁻¹ ^ c := T.measure_le c

/-- **Martin-Löf randomness**: `X` escapes every Martin-Löf test. -/
def MLRandom (X : ℕ → Bool) : Prop := ∀ T : MLTest, ∃ c, X ∉ T.level c

------------------------------------------------------------------------
-- Prefixes
------------------------------------------------------------------------

/-- The first `n` bits of `X`, as a finite string. -/
def prefixList (X : ℕ → Bool) (n : ℕ) : List Bool := (List.range n).map X

@[simp] theorem prefixList_length (X : ℕ → Bool) (n : ℕ) : (prefixList X n).length = n := by
  simp [prefixList]

@[simp] theorem prefixList_getElem (X : ℕ → Bool) (n i : ℕ) (h : i < (prefixList X n).length) :
    (prefixList X n)[i] = X i := by
  simp [prefixList]

theorem mem_cylinder_prefixList (X : ℕ → Bool) (n : ℕ) : X ∈ cylinder (prefixList X n) :=
  fun i hi => (prefixList_getElem X n i hi).symm

theorem prefixList_prefix {X : ℕ → Bool} {m n : ℕ} (h : m ≤ n) :
    prefixList X m <+: prefixList X n := by
  have h2 : List.range m <+: List.range n := by
    have := List.take_prefix m (List.range n)
    rwa [List.take_range, Nat.min_eq_left h] at this
  exact h2.map X

/-- Membership in a cylinder says exactly that the string is an initial segment. -/
theorem prefixList_eq_of_mem_cylinder {X : ℕ → Bool} {σ : List Bool} (h : X ∈ cylinder σ) :
    prefixList X σ.length = σ := by
  refine List.ext_getElem (by simp) fun i h1 h2 => ?_
  have hi : i < σ.length := by simpa using h2
  simpa using h i hi

/-- Two initial segments of the same sequence are comparable. -/
theorem prefix_of_mem_cylinder {X : ℕ → Bool} {σ τ : List Bool}
    (hσ : X ∈ cylinder σ) (hτ : X ∈ cylinder τ) (h : σ.length ≤ τ.length) : σ <+: τ := by
  simpa [prefixList_eq_of_mem_cylinder hσ, prefixList_eq_of_mem_cylinder hτ] using
    prefixList_prefix (X := X) h

/-- Incomparable strings have disjoint cylinders. -/
theorem disjoint_cylinder {σ τ : List Bool} (hlen : σ.length ≤ τ.length) (h : ¬ σ <+: τ) :
    Disjoint (cylinder σ) (cylinder τ) := by
  rw [Set.disjoint_left]
  intro X hσ hτ
  exact h (prefix_of_mem_cylinder hσ hτ hlen)

/-- **Kraft's inequality, measure-theoretically**: the weights of finitely many pairwise disjoint
cylinders inside a set `A` add up to at most the measure of `A`. -/
theorem sum_two_inv_pow_length_le {S : Finset (List Bool)} {A : Set (ℕ → Bool)}
    (hdisj : ∀ σ ∈ S, ∀ τ ∈ S, σ ≠ τ → Disjoint (cylinder σ) (cylinder τ))
    (hsub : ∀ σ ∈ S, cylinder σ ⊆ A) :
    ∑ σ ∈ S, (2 : ENNReal)⁻¹ ^ σ.length ≤ cantorMeasure A := by
  have hpair : (↑S : Set (List Bool)).Pairwise (Function.onFun Disjoint cylinder) := by
    intro σ hσ τ hτ hne
    exact hdisj σ (by simpa using hσ) τ (by simpa using hτ) hne
  have hunion : cantorMeasure (⋃ σ ∈ S, cylinder σ) = ∑ σ ∈ S, cantorMeasure (cylinder σ) :=
    measure_biUnion_finset hpair fun σ _ => measurableSet_cylinder σ
  calc ∑ σ ∈ S, (2 : ENNReal)⁻¹ ^ σ.length
      = ∑ σ ∈ S, cantorMeasure (cylinder σ) :=
        Finset.sum_congr rfl fun σ _ => (cantorMeasure_cylinder σ).symm
    _ = cantorMeasure (⋃ σ ∈ S, cylinder σ) := hunion.symm
    _ ≤ cantorMeasure A := measure_mono (Set.iUnion₂_subset hsub)

------------------------------------------------------------------------
-- No computable sequence is random
------------------------------------------------------------------------

theorem computable_prefixList {X : ℕ → Bool} (h : Computable X) :
    Computable fun n : ℕ => prefixList X n := by
  have key : Computable₂ fun (_ : ℕ) (p : ℕ × List Bool) => p.2 ++ [X p.1] :=
    Computable₂.comp Computable.list_append (Computable.snd.comp Computable.snd)
      (Computable.list_cons.comp (h.comp (Computable.fst.comp Computable.snd))
        (Computable.const ([] : List Bool)))
  have hrec := Computable.nat_rec (f := fun n : ℕ => n)
    (g := fun _ : ℕ => ([] : List Bool)) Computable.id (Computable.const _) key
  refine hrec.of_eq fun n => ?_
  induction n with
  | zero => simp [prefixList]
  | succ n ih => simp [prefixList, List.range_succ] at ih ⊢; simp [ih]

/-- Deciding equality with a computable string-valued function is computable. -/
theorem computable_decide_eq_string {f : ℕ × List Bool × ℕ → List Bool} (hf : Computable f) :
    Computable fun p : ℕ × List Bool × ℕ => decide (p.2.1 = f p) :=
  Computable₂.comp (Primrec₂.to_comp (Primrec.eq (α := List Bool)).decide)
    (Computable.fst.comp Computable.snd) hf

/-- The enumeration matrix of `Lambda.prefixTest`. -/
def prefixEnter (X : ℕ → Bool) (c : ℕ) (σ : List Bool) (j : ℕ) : Bool :=
  decide (σ = prefixList X (c + j))

theorem prefixEnter_computable {X : ℕ → Bool} (h : Computable X) :
    Computable fun p : ℕ × List Bool × ℕ => prefixEnter X p.1 p.2.1 p.2.2 := by
  have hadd : Computable fun p : ℕ × List Bool × ℕ => p.1 + p.2.2 :=
    Computable₂.comp (Primrec₂.to_comp Primrec.nat_add) Computable.fst
      (Computable.snd.comp Computable.snd)
  exact computable_decide_eq_string (Computable.comp (computable_prefixList h) hadd)

theorem openOf_prefixEnter (X : ℕ → Bool) (c : ℕ) :
    openOf {σ | ∃ j, prefixEnter X c σ j = Bool.true} = cylinder (prefixList X c) := by
  ext Y
  simp only [mem_openOf, prefixEnter, Set.mem_setOf_eq, decide_eq_true_eq]
  refine ⟨?_, fun hY => ⟨prefixList X c, ⟨0, by simp⟩, hY⟩⟩
  rintro ⟨σ, ⟨j, rfl⟩, hY⟩
  exact cylinder_mono (prefixList_prefix (Nat.le_add_right c j)) hY

/-- The Martin-Löf test that catches a fixed computable sequence: level `c` enumerates all
prefixes of `X` of length at least `c`. -/
def prefixTest {X : ℕ → Bool} (h : Computable X) : MLTest where
  enter := prefixEnter X
  enter_computable := prefixEnter_computable h
  measure_le c := by
    rw [openOf_prefixEnter, cantorMeasure_cylinder, prefixList_length]

/-- **No computable sequence is Martin-Löf random.** -/
theorem not_mlRandom_of_computable {X : ℕ → Bool} (h : Computable X) : ¬ MLRandom X := by
  intro hr
  obtain ⟨c, hc⟩ := hr (prefixTest h)
  refine hc ?_
  rw [MLTest.level, MLTest.strings]
  change X ∈ openOf {σ | ∃ j, prefixEnter X c σ j = Bool.true}
  rw [openOf_prefixEnter]
  exact mem_cylinder_prefixList X c

------------------------------------------------------------------------
-- Kraft's inequality in `ℝ≥0∞`
------------------------------------------------------------------------

theorem ennreal_two_inv_pow (k : ℕ) : (2 : ENNReal)⁻¹ ^ k = ENNReal.ofReal ((2 : ℝ)⁻¹ ^ k) := by
  rw [ENNReal.ofReal_pow (by norm_num)]
  congr 1
  rw [ENNReal.ofReal_inv_of_pos (by norm_num)]
  norm_num

/-- **Kraft's inequality for prefix complexity, in `ℝ≥0∞`.** -/
theorem kraft_kolmP_ennreal : ∑' s : ℕ, (2 : ENNReal)⁻¹ ^ kolmP s ≤ 1 := by
  simp only [ennreal_two_inv_pow]
  rw [ENNReal.tsum_eq_iSup_sum]
  refine iSup_le fun F => ?_
  rw [← ENNReal.ofReal_sum_of_nonneg fun i _ => by positivity]
  refine ENNReal.ofReal_le_one.2 ?_
  have h := Kraft.sum_wt_le_one shortestProgram_prefixFreeCoding F
  have hrw : ∀ s : ℕ, Kraft.wt (bits (shortestProgram s)) = ((2 : ℝ)⁻¹) ^ kolmP s := by
    intro s
    rw [Kraft.wt, (shortestProgram_spec s).2]
  simpa [hrw] using h

------------------------------------------------------------------------
-- The compression test
------------------------------------------------------------------------

/-- `e` is the code of a closed term of at most `L` bits which reaches the Church numeral of `m`
in `i` leftmost steps. -/
def ShortProg (L m e i : ℕ) : Prop :=
  is_valid_code e = Bool.true ∧ freeMax_code e = 0 ∧ bitsLen_code e < L ∧
    nstep_code^[i] e = Lambda.church_code m

instance (L m e i : ℕ) : Decidable (ShortProg L m e i) := by unfold ShortProg; infer_instance

/-- A closed term with a Church numeral as normal form reaches it along the leftmost run. -/
theorem exists_iterate_eq_church_of_isProgramFor {t : Lambda} {m : ℕ} (h : IsProgramFor t m) :
    ∃ i, nstep^[i] t = Lambda.church m :=
  ⟨haltTime t, nf_eq_of_reduces_normal h.2 (Lambda.church_normal m)⟩

theorem exists_shortProg_iff (L m : ℕ) :
    (∃ e i, ShortProg L m e i) ↔ kolmP m < L := by
  constructor
  · rintro ⟨e, i, hvalid, hfree, hlen, hstep⟩
    set t : Lambda := decodeD e with ht
    have hte : Lambda.encode t = e := encode_decodeD hvalid
    have hclosed : IsClosed t := by
      refine (isClosed_iff_freeMax_eq_zero t).2 ?_
      rw [← freeMax_code_correct t, hte]
      exact hfree
    have hiter : nstep^[i] t = Lambda.church m := by
      apply Lambda.encode_injective
      rw [← nstep_code_iterate, hte, hstep, encode_church_eq_church_code]
    have hprog : IsProgramFor t m := ⟨hclosed, hiter ▸ reduces_nstep_iterate t i⟩
    have := kolmP_le_of_isProgramFor hprog
    have hbits : (bits t).length = bitsLen_code e := by rw [← hte, bitsLen_code_correct]
    omega
  · intro hlt
    obtain ⟨t, hprog, hbits⟩ := exists_program_of_kolmP m
    obtain ⟨i, hi⟩ := exists_iterate_eq_church_of_isProgramFor hprog
    refine ⟨Lambda.encode t, i, is_valid_code_encode t, ?_, ?_, ?_⟩
    · rw [freeMax_code_correct]
      exact (isClosed_iff_freeMax_eq_zero t).1 hprog.1
    · rw [bitsLen_code_correct, hbits]; exact hlt
    · rw [nstep_code_iterate, hi, encode_church_eq_church_code]

/-- The four clauses of `Lambda.ShortProg` are primitive recursive in all their arguments.  The
variable layout is `q = (i, (e, (c, σ, j)))`. -/
theorem primrec_shortProg :
    PrimrecPred fun q : ℕ × (ℕ × (ℕ × List Bool × ℕ)) =>
      ShortProg (q.2.2.2.1.length - q.2.2.1) (Encodable.encode q.2.2.2.1) q.2.1 q.1 := by
  have hi : Primrec fun q : ℕ × (ℕ × (ℕ × List Bool × ℕ)) => q.1 := Primrec.fst
  have he : Primrec fun q : ℕ × (ℕ × (ℕ × List Bool × ℕ)) => q.2.1 :=
    Primrec.fst.comp Primrec.snd
  have hc : Primrec fun q : ℕ × (ℕ × (ℕ × List Bool × ℕ)) => q.2.2.1 :=
    Primrec.fst.comp (Primrec.snd.comp Primrec.snd)
  have hsig : Primrec fun q : ℕ × (ℕ × (ℕ × List Bool × ℕ)) => q.2.2.2.1 :=
    Primrec.fst.comp (Primrec.snd.comp (Primrec.snd.comp Primrec.snd))
  have hA : PrimrecPred fun q : ℕ × (ℕ × (ℕ × List Bool × ℕ)) =>
      is_valid_code q.2.1 = Bool.true :=
    PrimrecRel.comp (Primrec.eq (α := Bool)) (Lambda.is_valid_code_primrec.comp he)
      (Primrec.const Bool.true)
  have hB : PrimrecPred fun q : ℕ × (ℕ × (ℕ × List Bool × ℕ)) => freeMax_code q.2.1 = 0 :=
    PrimrecRel.comp (Primrec.eq (α := ℕ)) (freeMax_code_primrec.comp he) (Primrec.const 0)
  have hC : PrimrecPred fun q : ℕ × (ℕ × (ℕ × List Bool × ℕ)) =>
      bitsLen_code q.2.1 < q.2.2.2.1.length - q.2.2.1 :=
    PrimrecRel.comp Primrec.nat_lt (bitsLen_code_primrec.comp he)
      (Primrec.nat_sub.comp (Primrec.list_length.comp hsig) hc)
  have hD : PrimrecPred fun q : ℕ × (ℕ × (ℕ × List Bool × ℕ)) =>
      nstep_code^[q.1] q.2.1 = Lambda.church_code (Encodable.encode q.2.2.2.1) :=
    PrimrecRel.comp (Primrec.eq (α := ℕ)) (nstep_code_iterate_primrec.comp he hi)
      (Lambda.church_code_primrec.comp (Primrec.encode.comp hsig))
  exact (hA.and (hB.and (hC.and hD))).of_eq fun q => by rw [ShortProg]

/-- The compression test: level `c` collects the strings compressible by more than `c` bits. -/
def compressEnter (c : ℕ) (σ : List Bool) (j : ℕ) : Bool :=
  decide (∃ e < j, ∃ i < j, ShortProg (σ.length - c) (Encodable.encode σ) e i)

theorem primrec_compressEnter :
    PrimrecPred fun p : ℕ × List Bool × ℕ =>
      ∃ e < p.2.2, ∃ i < p.2.2,
        ShortProg (p.2.1.length - p.1) (Encodable.encode p.2.1) e i := by
  have hex1 : PrimrecPred fun b : ℕ × (ℕ × List Bool × ℕ) =>
      ∃ i < b.2.2.2, ShortProg (b.2.2.1.length - b.2.1) (Encodable.encode b.2.2.1) b.1 i :=
    primrecPred_exists_lt primrec_shortProg.primrecRel
      (Primrec.snd.comp (Primrec.snd.comp Primrec.snd))
  exact primrecPred_exists_lt hex1.primrecRel (Primrec.snd.comp Primrec.snd)

theorem compressEnter_computable :
    Computable fun p : ℕ × List Bool × ℕ => compressEnter p.1 p.2.1 p.2.2 :=
  (Primrec.to_comp primrec_compressEnter.decide).of_eq fun _ => rfl

theorem exists_compressEnter_iff (c : ℕ) (σ : List Bool) :
    (∃ j, compressEnter c σ j = Bool.true) ↔ kolmP (Encodable.encode σ) + c < σ.length := by
  simp only [compressEnter, decide_eq_true_eq]
  have hiff := exists_shortProg_iff (σ.length - c) (Encodable.encode σ)
  constructor
  · rintro ⟨j, e, -, i, -, h⟩
    have := hiff.1 ⟨e, i, h⟩
    omega
  · intro hlt
    obtain ⟨e, i, h⟩ := hiff.2 (by omega)
    exact ⟨max e i + 1, e, by omega, i, by omega, h⟩

theorem compress_strings_eq (c : ℕ) :
    {σ : List Bool | ∃ j, compressEnter c σ j = Bool.true}
      = {σ : List Bool | kolmP (Encodable.encode σ) + c < σ.length} := by
  ext σ
  exact exists_compressEnter_iff c σ

theorem cantorMeasure_compress_le (c : ℕ) :
    cantorMeasure (openOf {σ | ∃ j, compressEnter c σ j = Bool.true}) ≤ (2 : ENNReal)⁻¹ ^ c := by
  rw [compress_strings_eq]
  set W : Set (List Bool) := {σ : List Bool | kolmP (Encodable.encode σ) + c < σ.length} with hW
  refine le_trans (cantorMeasure_openOf_le W) ?_
  have hterm : ∀ σ : W, (2 : ENNReal)⁻¹ ^ (σ : List Bool).length ≤
      (2 : ENNReal)⁻¹ ^ (c + 1) * (2 : ENNReal)⁻¹ ^ kolmP (Encodable.encode (σ : List Bool)) := by
    intro τ
    have h : kolmP (Encodable.encode (τ : List Bool)) + c < (τ : List Bool).length := τ.2
    rw [← pow_add]
    exact pow_le_pow_right_of_le_one' (by norm_num) (by omega)
  refine le_trans (ENNReal.tsum_le_tsum hterm) ?_
  rw [ENNReal.tsum_mul_left]
  have hinj : Function.Injective fun σ : W => Encodable.encode (σ : List Bool) :=
    fun _ _ h => Subtype.ext (Encodable.encode_injective h)
  have hsum : ∑' σ : W, (2 : ENNReal)⁻¹ ^ kolmP (Encodable.encode (σ : List Bool)) ≤ 1 :=
    le_trans (ENNReal.tsum_comp_le_tsum_of_injective hinj fun s => (2 : ENNReal)⁻¹ ^ kolmP s)
      kraft_kolmP_ennreal
  calc (2 : ENNReal)⁻¹ ^ (c + 1) *
        ∑' σ : W, (2 : ENNReal)⁻¹ ^ kolmP (Encodable.encode (σ : List Bool))
      ≤ (2 : ENNReal)⁻¹ ^ (c + 1) * 1 := by gcongr
    _ ≤ (2 : ENNReal)⁻¹ ^ c := by
        rw [mul_one]
        exact pow_le_pow_right_of_le_one' (by norm_num) (by omega)

/-- The Martin-Löf test built from compressibility by the lambda machine. -/
def compressTest : MLTest where
  enter := compressEnter
  enter_computable := compressEnter_computable
  measure_le := cantorMeasure_compress_le

------------------------------------------------------------------------
-- The easy half of the Levin-Schnorr theorem
------------------------------------------------------------------------

/-- **Martin-Löf random sequences have incompressible prefixes.**  This is the direction of the
Levin–Schnorr theorem that only needs Kraft's inequality. -/
theorem exists_const_le_kolmP_prefix_of_mlRandom {X : ℕ → Bool} (h : MLRandom X) :
    ∃ c : ℕ, ∀ n : ℕ, n ≤ kolmP (Encodable.encode (prefixList X n)) + c := by
  obtain ⟨c, hc⟩ := h compressTest
  refine ⟨c, fun n => ?_⟩
  by_contra hcon
  refine hc (mem_openOf.2 ⟨prefixList X n, ?_, mem_cylinder_prefixList X n⟩)
  refine (exists_compressEnter_iff c (prefixList X n)).2 ?_
  rw [prefixList_length]
  omega

end

end Lambda
