/-
Abstract rewriting: one interface for the confluence combinators of the calculi.

Every calculus in this library re-derives the same rewriting theory over its own syntax: a
reflexive–transitive closure with its `trans`/`head`/`single` lemmas, the diamond property, the
strip lemma, commutation, η-postponement, a measure argument for termination, Newman's lemma.
`docs/consolidation-review.md` counts fourteen hand-rolled closures and four
parallel-reduction developments.  This module proves those statements once, for an arbitrary
relation `r : α → α → Prop`; a client keeps its own inductive closure and needs only a bridging
lemma `Red t u ↔ Star Step t u` in order to use them.

* `Rewriting.Star`, `Rewriting.Plus`, `Rewriting.Conv`, `Rewriting.Alt` — the reflexive–transitive
  closure, the transitive closure, the generated conversion and the union of two relations, with
  the closure API (`Star.trans`, `Star.head`, `Star.single`, `Star.head_split`, `Star.mono`);
* `Rewriting.Diamond`, `Confluent`, `LocallyConfluent`, `Commute`, `StronglyCommute`, `Postpones`,
  `SN`, `Terminating` — the properties;
* `Rewriting.strip`, `Rewriting.confluent_of_diamond` — the diamond property implies confluence,
  and `Rewriting.confluent_of_diamond_of_between` — the Tait–Martin-Löf argument: a relation with
  a parallel reduction between it and its closure that has the diamond property is confluent;
* `Rewriting.conv_iff_joins_of_confluent` — for a confluent relation, conversion is joinability;
* `Rewriting.commute_of_stronglyCommute` — Hindley's strong commutation lemma;
* `Rewriting.confluent_alt_of_commute` — **Hindley–Rosen**: two confluent commuting relations have
  a confluent union;
* `Rewriting.postpone_par_star`, `Rewriting.postpones_of_par`, `Rewriting.postponesPlus_of_par` —
  local postponement for a parallel relation gives postponement, in the plain and in the
  "at least one step" form;
* `Rewriting.star_alt_iff_of_postpones` — postponement in the form `(r ∪ s)* = r* ; s*`;
* `Rewriting.terminating_of_measure`, `Rewriting.sn_alt_of_postponesPlus` — termination from a
  measure, and termination of a union from termination of one half plus postponement;
* `Rewriting.confluent_of_sn`, `Rewriting.confluent_of_newman` — **Newman's lemma**.

The clients are `Start/Reduction.lean`, `Start/SystemTConfluence.lean`,
`Start/SystemFCConfluence.lean`, `Start/LambdaPi.lean`, `Start/LambdaBetaEta.lean`,
`Start/LambdaEtaPostpone.lean`, `Start/LambdaPiEtaPostpone.lean` and
`Start/LambdaPiEtaConfluent.lean`; each keeps its own inductive closure and bridges to `Star` with
one lemma.
-/

import Mathlib.Logic.Relation
import Mathlib.Tactic

set_option relaxedAutoImplicit false
set_option autoImplicit false

namespace Rewriting

variable {α : Type*} {r s : α → α → Prop}

/-! ### The closures -/

/-- The reflexive–transitive closure of `r`: a reduction of zero or more steps. -/
def Star (r : α → α → Prop) : α → α → Prop := Relation.ReflTransGen r

/-- The transitive closure of `r`: a reduction of at least one step. -/
def Plus (r : α → α → Prop) : α → α → Prop := Relation.TransGen r

/-- The union of two rewrite relations. -/
def Alt (r s : α → α → Prop) : α → α → Prop := fun a b => r a b ∨ s a b

/-- The conversion generated by `r`: the equivalence relation obtained by allowing steps of `r`
in both directions. -/
def Conv (r : α → α → Prop) : α → α → Prop := Star (Alt r (fun a b => r b a))

/-- `a` and `b` have a common reduct. -/
def Joins (r : α → α → Prop) (a b : α) : Prop := ∃ c, Star r a c ∧ Star r b c

theorem Star.refl (a : α) : Star r a a := Relation.ReflTransGen.refl

theorem Star.single {a b : α} (h : r a b) : Star r a b := Relation.ReflTransGen.single h

theorem Star.trans {a b c : α} (h₁ : Star r a b) (h₂ : Star r b c) : Star r a c :=
  Relation.ReflTransGen.trans h₁ h₂

theorem Star.head {a b c : α} (h₁ : r a b) (h₂ : Star r b c) : Star r a c :=
  Relation.ReflTransGen.head h₁ h₂

theorem Star.tail {a b c : α} (h₁ : Star r a b) (h₂ : r b c) : Star r a c :=
  Relation.ReflTransGen.tail h₁ h₂

/-- Induction on a reduction from the tail end. -/
@[elab_as_elim]
theorem Star.rec_tail {a : α} {motive : ∀ b : α, Star r a b → Prop}
    (refl : motive a (Star.refl a))
    (tail : ∀ {b c : α} (hab : Star r a b) (hbc : r b c), motive b hab →
      motive c (hab.tail hbc)) :
    ∀ {b : α} (hab : Star r a b), motive b hab := by
  intro b hab
  induction hab with
  | refl => exact refl
  | tail h₁ h₂ ih => exact tail _ h₂ ih

/-- A reduction is either empty or begins with a step. -/
theorem Star.cases_head {a b : α} (h : Star r a b) : a = b ∨ ∃ c, r a c ∧ Star r c b :=
  Relation.ReflTransGen.cases_head h

/-- A nonempty reduction can be split at its first step. -/
theorem Star.head_split {a b c : α} (h : Star r a b) (hb : r b c) :
    ∃ a₁, r a a₁ ∧ Star r a₁ c := by
  have : Plus r a c := Relation.TransGen.tail' h hb
  exact (Relation.TransGen.head'_iff).1 this

theorem Star.mono {r' : α → α → Prop} (h : ∀ a b, r a b → r' a b) {a b : α} (hab : Star r a b) :
    Star r' a b := by
  induction hab with
  | refl => exact Star.refl a
  | tail _ hbc ih => exact ih.tail (h _ _ hbc)

/-- Two relations with the same steps have the same closure. -/
theorem star_congr {r' : α → α → Prop} (h : ∀ a b, r a b ↔ r' a b) (a b : α) :
    Star r a b ↔ Star r' a b :=
  ⟨Star.mono fun _ _ hab => (h _ _).1 hab, Star.mono fun _ _ hab => (h _ _).2 hab⟩

theorem Plus.single {a b : α} (h : r a b) : Plus r a b := Relation.TransGen.single h

theorem Plus.toStar {a b : α} (h : Plus r a b) : Star r a b := h.to_reflTransGen

theorem Plus.trans {a b c : α} (h₁ : Plus r a b) (h₂ : Plus r b c) : Plus r a c :=
  Relation.TransGen.trans h₁ h₂

theorem Plus.of_star_tail {a b c : α} (h : Star r a b) (hb : r b c) : Plus r a c :=
  Relation.TransGen.tail' h hb

theorem Plus.head_split {a b : α} (h : Plus r a b) : ∃ c, r a c ∧ Star r c b :=
  (Relation.TransGen.head'_iff).1 h

theorem Plus.trans_star {a b c : α} (h₁ : Plus r a b) (h₂ : Star r b c) : Plus r a c :=
  Relation.TransGen.trans_left h₁ h₂

theorem Star.toConv {a b : α} (h : Star r a b) : Conv r a b :=
  Star.mono (fun _ _ hab => Or.inl hab) h

theorem Conv.refl (a : α) : Conv r a a := Star.refl a

theorem Conv.single {a b : α} (h : r a b) : Conv r a b := Star.single (Or.inl h)

theorem Conv.trans {a b c : α} (h₁ : Conv r a b) (h₂ : Conv r b c) : Conv r a c := Star.trans h₁ h₂

theorem Conv.symm {a b : α} (h : Conv r a b) : Conv r b a := by
  induction h with
  | refl => exact Conv.refl a
  | tail _ hbc ih =>
      refine Star.head ?_ ih
      exact hbc.symm

theorem Conv.of_joins {a b : α} (h : Joins r a b) : Conv r a b := by
  obtain ⟨c, hac, hbc⟩ := h
  exact hac.toConv.trans hbc.toConv.symm

/-! ### The properties -/

/-- The diamond property: two steps out of the same point can be joined by one step each. -/
def Diamond (r : α → α → Prop) : Prop :=
  ∀ ⦃a b c : α⦄, r a b → r a c → ∃ d, r b d ∧ r c d

/-- Confluence: the diamond property of the reflexive–transitive closure. -/
def Confluent (r : α → α → Prop) : Prop := Diamond (Star r)

/-- Local confluence: two single steps out of the same point can be joined by reductions. -/
def LocallyConfluent (r : α → α → Prop) : Prop :=
  ∀ ⦃a b c : α⦄, r a b → r a c → Joins r b c

/-- Two relations commute when their closures can always be joined. -/
def Commute (r s : α → α → Prop) : Prop :=
  ∀ ⦃a b c : α⦄, Star r a b → Star s a c → ∃ d, Star s b d ∧ Star r c d

/-- Hindley's strong commutation: an `r`-step and an `s`-step out of the same point are joined by
`s`-steps on one side and *at most one* `r`-step on the other. -/
def StronglyCommute (r s : α → α → Prop) : Prop :=
  ∀ ⦃a b c : α⦄, r a b → s a c → ∃ d, Star s b d ∧ Relation.ReflGen r c d

/-- `s` postpones after `r`: an `s`-reduction followed by an `r`-step can be rearranged into an
`r`-reduction followed by an `s`-reduction. -/
def Postpones (s r : α → α → Prop) : Prop :=
  ∀ ⦃a b c : α⦄, Star s a b → r b c → ∃ d, Star r a d ∧ Star s d c

/-- The sharper form of postponement, in which the rearranged `r`-reduction is nonempty; this is
what a termination argument needs. -/
def PostponesPlus (s r : α → α → Prop) : Prop :=
  ∀ ⦃a b c : α⦄, Star s a b → r b c → ∃ d, Plus r a d ∧ Star s d c

/-- `a` is strongly normalizing for `r`: no infinite `r`-reduction starts at `a`. -/
def SN (r : α → α → Prop) (a : α) : Prop := Acc (fun x y => r y x) a

/-- `r` terminates when every point is strongly normalizing. -/
def Terminating (r : α → α → Prop) : Prop := ∀ a, SN r a

theorem SN.intro {a : α} (h : ∀ b, r a b → SN r b) : SN r a := Acc.intro a h

theorem SN.step {a b : α} (h : SN r a) (hab : r a b) : SN r b := h.inv hab

theorem SN.star {a b : α} (h : SN r a) (hab : Star r a b) : SN r b := by
  induction hab with
  | refl => exact h
  | tail _ hbc ih => exact ih.step hbc

theorem PostponesPlus.toPostpones (h : PostponesPlus s r) : Postpones s r := by
  intro a b c hab hbc
  obtain ⟨d, hd, hdc⟩ := h hab hbc
  exact ⟨d, hd.toStar, hdc⟩

/-! ### The diamond property implies confluence -/

/-- **The strip lemma**: a single step and a reduction out of the same point can be joined, one
side remaining a single step. -/
theorem strip (hd : Diamond r) : ∀ {a b c : α}, r a b → Star r a c → ∃ d, Star r b d ∧ r c d := by
  intro a b c hab hac
  induction hac generalizing b with
  | refl => exact ⟨b, Star.refl b, hab⟩
  | @tail c₁ c₂ _ hc₁c₂ ih =>
      obtain ⟨d₁, hbd₁, hc₁d₁⟩ := ih hab
      obtain ⟨d, hd₁d, hc₂d⟩ := hd hc₁d₁ hc₁c₂
      exact ⟨d, hbd₁.tail hd₁d, hc₂d⟩

/-- A relation with the diamond property is confluent. -/
theorem confluent_of_diamond (hd : Diamond r) : Confluent r := by
  intro a b c hab hac
  induction hab generalizing c with
  | refl => exact ⟨c, hac, Star.refl c⟩
  | @tail b₁ b₂ _ hb₁b₂ ih =>
      obtain ⟨d₁, hb₁d₁, hcd₁⟩ := ih hac
      obtain ⟨d, hb₂d, hd₁d⟩ := strip hd hb₁b₂ hb₁d₁
      exact ⟨d, hb₂d, hcd₁.tail hd₁d⟩

/-- Confluence transfers along an equality of closures. -/
theorem confluent_of_star_iff {r' : α → α → Prop} (h : ∀ a b, Star r a b ↔ Star r' a b)
    (hc : Confluent r) : Confluent r' := by
  intro a b c hab hac
  obtain ⟨d, hbd, hcd⟩ := hc ((h a b).2 hab) ((h a c).2 hac)
  exact ⟨d, (h b d).1 hbd, (h c d).1 hcd⟩

/-- The Church–Rosser property: for a confluent relation, conversion is joinability. -/
theorem conv_iff_joins_of_confluent (hc : Confluent r) {a b : α} :
    Conv r a b ↔ Joins r a b := by
  constructor
  · intro h
    induction h with
    | refl => exact ⟨a, Star.refl a, Star.refl a⟩
    | @tail b₁ b₂ _ hb₁b₂ ih =>
        obtain ⟨d, had, hb₁d⟩ := ih
        rcases hb₁b₂ with hb | hb
        · obtain ⟨e, hde, hb₂e⟩ := hc hb₁d (Star.single hb)
          exact ⟨e, had.trans hde, hb₂e⟩
        · exact ⟨d, had, Star.head hb hb₁d⟩
  · exact Conv.of_joins

/-! ### Confluence through a parallel relation -/

section Between

variable {p : α → α → Prop}

/-- A relation squeezed between `r` and its closure has the same closure. -/
theorem star_eq_of_between (h₁ : ∀ {a b : α}, r a b → p a b)
    (h₂ : ∀ {a b : α}, p a b → Star r a b) (a b : α) : Star p a b ↔ Star r a b := by
  constructor
  · intro h
    induction h with
    | refl => exact Star.refl a
    | tail _ hbc ih => exact ih.trans (h₂ hbc)
  · exact Star.mono (fun _ _ hab => h₁ hab)

/-- The strip lemma in its mixed form: one step of a parallel relation `p` with the diamond
property against a reduction of `r`. -/
theorem strip_of_between (hd : Diamond p) (h₁ : ∀ {a b : α}, r a b → p a b)
    (h₂ : ∀ {a b : α}, p a b → Star r a b) :
    ∀ {a b c : α}, p a b → Star r a c → ∃ d, Star r b d ∧ p c d := by
  intro a b c hab hac
  induction hac generalizing b with
  | refl => exact ⟨b, Star.refl b, hab⟩
  | @tail c₁ c₂ _ hc₁c₂ ih =>
      obtain ⟨d₁, hbd₁, hc₁d₁⟩ := ih hab
      obtain ⟨e, hd₁e, hc₂e⟩ := hd hc₁d₁ (h₁ hc₁c₂)
      exact ⟨e, hbd₁.trans (h₂ hd₁e), hc₂e⟩

/-- **Confluence through a parallel reduction**: if some relation between `r` and `r*` has the
diamond property, then `r` is confluent.  This is the Tait–Martin-Löf argument, once and for all. -/
theorem confluent_of_diamond_of_between (hd : Diamond p) (h₁ : ∀ {a b : α}, r a b → p a b)
    (h₂ : ∀ {a b : α}, p a b → Star r a b) : Confluent r :=
  confluent_of_star_iff (star_eq_of_between h₁ h₂) (confluent_of_diamond hd)

end Between

/-! ### Commutation -/

/-- The commutation strip: one `r`-step against an `s`-reduction. -/
theorem strip_stronglyCommute (h : StronglyCommute r s) :
    ∀ {a b c : α}, r a b → Star s a c → ∃ d, Star s b d ∧ Relation.ReflGen r c d := by
  intro a b c hab hac
  induction hac with
  | refl => exact ⟨b, Star.refl b, Relation.ReflGen.single hab⟩
  | @tail c₁ c₂ _ hc₁c₂ ih =>
      obtain ⟨d₁, hbd₁, hc₁d₁⟩ := ih
      cases hc₁d₁ with
      | refl => exact ⟨c₂, hbd₁.tail hc₁c₂, Relation.ReflGen.refl⟩
      | single hrc =>
          obtain ⟨d, hd₁d, hc₂d⟩ := h hrc hc₁c₂
          exact ⟨d, hbd₁.trans hd₁d, hc₂d⟩

/-- **Hindley's commutation lemma**: strongly commuting relations have commuting closures. -/
theorem commute_of_stronglyCommute (h : StronglyCommute r s) : Commute r s := by
  intro a b c hab hac
  induction hab generalizing c with
  | refl => exact ⟨c, hac, Star.refl c⟩
  | @tail b₁ b₂ _ hb₁b₂ ih =>
      obtain ⟨d₁, hb₁d₁, hcd₁⟩ := ih hac
      obtain ⟨d, hb₂d, hd₁d⟩ := strip_stronglyCommute h hb₁b₂ hb₁d₁
      refine ⟨d, hb₂d, ?_⟩
      cases hd₁d with
      | refl => exact hcd₁
      | single hd => exact hcd₁.tail hd

theorem Commute.symm (h : Commute r s) : Commute s r := by
  intro a b c hab hac
  obtain ⟨d, hbd, hcd⟩ := h hac hab
  exact ⟨d, hcd, hbd⟩

/-! ### Hindley–Rosen -/

theorem Star.toAlt_left {a b : α} (h : Star r a b) : Star (Alt r s) a b :=
  Star.mono (fun _ _ hab => Or.inl hab) h

theorem Star.toAlt_right {a b : α} (h : Star s a b) : Star (Alt r s) a b :=
  Star.mono (fun _ _ hab => Or.inr hab) h

/-- The composite `r* ; s*`, the relation whose closure is the closure of the union. -/
def Comp (r s : α → α → Prop) : α → α → Prop := fun a b => ∃ c, Star r a c ∧ Star s c b

theorem star_comp_eq_star_alt (a b : α) : Star (Comp r s) a b ↔ Star (Alt r s) a b := by
  constructor
  · intro h
    induction h with
    | refl => exact Star.refl a
    | tail _ hbc ih =>
        obtain ⟨e, hbe, hec⟩ := hbc
        exact ih.trans (hbe.toAlt_left.trans hec.toAlt_right)
  · intro h
    induction h with
    | refl => exact Star.refl a
    | tail _ hbc ih =>
        refine ih.tail ?_
        rcases hbc with hb | hb
        · exact ⟨_, Star.single hb, Star.refl _⟩
        · exact ⟨_, Star.refl _, Star.single hb⟩

/-- **Hindley–Rosen**: the union of two confluent commuting relations is confluent. -/
theorem confluent_alt_of_commute (hr : Confluent r) (hs : Confluent s) (hc : Commute r s) :
    Confluent (Alt r s) := by
  refine confluent_of_star_iff (fun a b => star_comp_eq_star_alt a b) (confluent_of_diamond ?_)
  rintro a b c ⟨x, hax, hxb⟩ ⟨y, hay, hyc⟩
  obtain ⟨p, hxp, hyp⟩ := hr hax hay
  obtain ⟨q, hpq, hbq⟩ := hc hxp hxb
  obtain ⟨q', hpq', hcq'⟩ := hc hyp hyc
  obtain ⟨d, hqd, hq'd⟩ := hs hpq hpq'
  exact ⟨d, ⟨q, hbq, hqd⟩, ⟨q', hcq', hq'd⟩⟩

/-! ### Postponement -/

section Par

variable {p : α → α → Prop}

/-- Local postponement propagates along an `r`-reduction: a `p`-step followed by an `r`-reduction
is an `r`-reduction followed by a `p`-step. -/
theorem postpone_par_star (hloc : ∀ {a b c : α}, p a b → r b c → ∃ d, Star r a d ∧ p d c) :
    ∀ {b c : α}, Star r b c → ∀ {a : α}, p a b → ∃ d, Star r a d ∧ p d c := by
  intro b c h
  induction h with
  | refl => exact fun {a} hab => ⟨a, Star.refl a, hab⟩
  | @tail c₁ c₂ _ hc₁c₂ ih =>
      intro a hab
      obtain ⟨d₁, had₁, hd₁c₁⟩ := ih hab
      obtain ⟨d, hd₁d, hdc₂⟩ := hloc hd₁c₁ hc₁c₂
      exact ⟨d, had₁.trans hd₁d, hdc₂⟩

/-- **Local postponement through a parallel relation**: if `p` sits between `s` and `s*` and a
`p`-step followed by an `r`-step can be rearranged into `r`-steps followed by a `p`-step, then `s`
postpones after `r`.  The parallel relation is what repairs the local diagram that a single
`s`-step usually fails. -/
theorem postpones_of_par (hstep : ∀ {a b : α}, s a b → p a b)
    (hsub : ∀ {a b : α}, p a b → Star s a b)
    (hloc : ∀ {a b c : α}, p a b → r b c → ∃ d, Star r a d ∧ p d c) :
    Postpones s r := by
  have key : ∀ {a b : α}, Star s a b → ∀ {c : α}, Star r b c → ∃ d, Star r a d ∧ Star s d c := by
    intro a b h
    induction h with
    | refl => exact fun {c} hc => ⟨c, hc, Star.refl c⟩
    | @tail b₀ b _ hs ih =>
        intro c hc
        obtain ⟨m₁, hm₁, hm₂⟩ := postpone_par_star hloc hc (hstep hs)
        obtain ⟨m, hm, hmm₁⟩ := ih hm₁
        exact ⟨m, hm, hmm₁.trans (hsub hm₂)⟩
  intro a b c hab hbc
  exact key hab (Star.single hbc)

/-- The same, sharpened: when the local diagram produces *at least one* `r`-step, so does the
rearrangement.  This is what the termination argument needs. -/
theorem postponesPlus_of_par (hstep : ∀ {a b : α}, s a b → p a b)
    (hsub : ∀ {a b : α}, p a b → Star s a b)
    (hloc : ∀ {a b c : α}, p a b → r b c → ∃ d, Plus r a d ∧ p d c) :
    PostponesPlus s r := by
  have hstar : ∀ {a b c : α}, p a b → Star r b c → ∃ d, Star r a d ∧ p d c :=
    fun hab hbc => postpone_par_star (fun k₁ k₂ => by
      obtain ⟨d, hd, hdc⟩ := hloc k₁ k₂
      exact ⟨d, hd.toStar, hdc⟩) hbc hab
  have hplus : ∀ {a b c : α}, p a b → Plus r b c → ∃ d, Plus r a d ∧ p d c := by
    intro a b c hab hbc
    obtain ⟨e, hbe, hec⟩ := hbc.head_split
    obtain ⟨d₁, had₁, hd₁e⟩ := hloc hab hbe
    obtain ⟨d, hd₁d, hdc⟩ := hstar hd₁e hec
    exact ⟨d, had₁.trans_star hd₁d, hdc⟩
  have key : ∀ {a b : α}, Star s a b → ∀ {c : α}, Plus r b c → ∃ d, Plus r a d ∧ Star s d c := by
    intro a b h
    induction h with
    | refl => exact fun {c} hc => ⟨c, hc, Star.refl c⟩
    | @tail b₀ b _ hs ih =>
        intro c hc
        obtain ⟨m₁, hm₁, hm₂⟩ := hplus (hstep hs) hc
        obtain ⟨m, hm, hmm₁⟩ := ih hm₁
        exact ⟨m, hm, hmm₁.trans (hsub hm₂)⟩
  intro a b c hab hbc
  exact key hab (Plus.single hbc)

end Par

/-- **Postponement**: if `s` postpones after `r` then every mixed reduction factors as an
`r`-reduction followed by an `s`-reduction. -/
theorem star_alt_iff_of_postpones (h : Postpones s r) {a b : α} :
    Star (Alt r s) a b ↔ ∃ c, Star r a c ∧ Star s c b := by
  constructor
  · intro hab
    induction hab with
    | refl => exact ⟨a, Star.refl a, Star.refl a⟩
    | @tail b₁ b₂ _ hb₁b₂ ih =>
        obtain ⟨c₁, hac₁, hc₁b₁⟩ := ih
        rcases hb₁b₂ with hb | hb
        · obtain ⟨d, hc₁d, hdb₂⟩ := h hc₁b₁ hb
          exact ⟨d, hac₁.trans hc₁d, hdb₂⟩
        · exact ⟨c₁, hac₁, hc₁b₁.tail hb⟩
  · rintro ⟨c, hac, hcb⟩
    exact hac.toAlt_left.trans hcb.toAlt_right

/-! ### Termination -/

/-- A relation that strictly decreases a natural-number measure terminates. -/
theorem terminating_of_measure (f : α → ℕ) (hf : ∀ {a b : α}, r a b → f b < f a) :
    Terminating r := by
  have key : ∀ n : ℕ, ∀ a : α, f a ≤ n → SN r a := by
    intro n
    induction n with
    | zero =>
        intro a ha
        refine SN.intro fun b hb => ?_
        exact absurd (hf hb) (by omega)
    | succ n ih =>
        intro a ha
        refine SN.intro fun b hb => ?_
        exact ih b (by have := hf hb; omega)
  intro a
  exact key (f a) a le_rfl

/-- Termination of a union, from termination of one half, a measure that the other half decreases,
and postponement in its sharp form.  The outer induction absorbs the `r`-steps by postponement,
the inner one is on the measure, which the `s`-steps decrease. -/
theorem sn_alt_aux (f : α → ℕ) (hf : ∀ {a b : α}, s a b → f b < f a) (hp : PostponesPlus s r) :
    ∀ {t : α}, SN r t → ∀ (n : ℕ) {m u : α}, Star r t m → Star s m u → f u ≤ n →
      SN (Alt r s) u := by
  intro t ht
  induction ht with
  | intro t _ ih =>
      intro n
      induction n with
      | zero =>
          intro m u hm hu hsize
          refine SN.intro ?_
          rintro w (hw | hw)
          · obtain ⟨d, hd, hdw⟩ := hp hu hw
            obtain ⟨m₁, hstep, hred⟩ := hd.head_split
            obtain ⟨t₁, ht₁, ht₁m⟩ := hm.head_split hstep
            exact ih t₁ ht₁ (f w) (ht₁m.trans hred) hdw le_rfl
          · exact absurd (hf hw) (by omega)
      | succ n ihn =>
          intro m u hm hu hsize
          refine SN.intro ?_
          rintro w (hw | hw)
          · obtain ⟨d, hd, hdw⟩ := hp hu hw
            obtain ⟨m₁, hstep, hred⟩ := hd.head_split
            obtain ⟨t₁, ht₁, ht₁m⟩ := hm.head_split hstep
            exact ih t₁ ht₁ (f w) (ht₁m.trans hred) hdw le_rfl
          · have := hf hw
            exact ihn hm (hu.tail hw) (by omega)

/-- A point that is strongly normalizing for `r` is strongly normalizing for the union, provided
`s` decreases a measure and postpones after `r`. -/
theorem sn_alt_of_postponesPlus (f : α → ℕ) (hf : ∀ {a b : α}, s a b → f b < f a)
    (hp : PostponesPlus s r) {t : α} (ht : SN r t) : SN (Alt r s) t :=
  sn_alt_aux f hf hp ht (f t) (Star.refl t) (Star.refl t) le_rfl

/-- Every strongly normalizing point has a normal form. -/
theorem exists_normal_of_sn {a : α} (h : SN r a) : ∃ b, Star r a b ∧ ∀ c, ¬ r b c := by
  induction h with
  | intro a _ ih =>
      by_cases hn : ∀ b, ¬ r a b
      · exact ⟨a, Star.refl a, hn⟩
      · obtain ⟨b, hb⟩ := not_forall.1 hn
        replace hb : r a b := not_not.1 hb
        obtain ⟨c, hbc, hc⟩ := ih b hb
        exact ⟨c, Star.head hb hbc, hc⟩

/-! ### Newman's lemma -/

/-- **Newman's lemma**, pointwise: a strongly normalizing point of a locally confluent relation is
confluent. -/
theorem confluent_of_sn (hlc : LocallyConfluent r) {a : α} (h : SN r a) :
    ∀ {b c : α}, Star r a b → Star r a c → Joins r b c := by
  induction h with
  | intro a _ ih =>
      intro b c hb hc
      rcases hb.cases_head with rfl | ⟨b₁, hab₁, hb₁b⟩
      · exact ⟨c, hc, Star.refl c⟩
      · rcases hc.cases_head with rfl | ⟨c₁, hac₁, hc₁c⟩
        · exact ⟨b, Star.refl b, Star.head hab₁ hb₁b⟩
        · obtain ⟨w, hw₁, hw₂⟩ := hlc hab₁ hac₁
          obtain ⟨u, hu₁, hu₂⟩ := ih b₁ hab₁ hb₁b hw₁
          obtain ⟨v, hv₁, hv₂⟩ := ih c₁ hac₁ hc₁c (hw₂.trans hu₂)
          exact ⟨v, hu₁.trans hv₂, hv₁⟩

/-- **Newman's lemma**: a terminating, locally confluent relation is confluent. -/
theorem confluent_of_newman (ht : Terminating r) (hlc : LocallyConfluent r) : Confluent r := by
  intro a b c hab hac
  exact confluent_of_sn hlc (ht a) hab hac

end Rewriting
