/-
Scott's `D∞`, step six: `⟦Ω⟧ = ⊥`, and the consistency of the lambda-eta calculus.

`Start/ScottDinfModel.lean` shows that `D∞` interprets the untyped calculus soundly for both
beta and eta.  This file computes the interpretation of the diverging term `Ω = (λx. x x)
(λx. x x)`: it is the least element of `D∞`.  Since `⟦I⟧ ≠ ⊥`, no lambda theory containing beta
and eta can identify `Ω` with `I`, which is a *semantic* consistency proof for the
**lambda-eta** calculus (the graph model of `Start/GraphModelSemantics.lean` only gives it for
beta, since that model is not extensional).

Main results:

* `ScottDinf.ddenot_omega`      — `⟦Ω⟧ρ = ⊥`;
* `ScottDinf.ddenot_I_ne_bot`   — `⟦I⟧ρ ≠ ⊥`;
* `ScottDinf.ConvBE`            — the compatible equivalence generated by beta and eta;
* `ScottDinf.not_convBE_omega_I`, `ScottDinf.convBE_consistent` — consistency of `λη`.
-/

import Start.ScottDinfModel
import Start.Recursion

set_option relaxedAutoImplicit false
set_option autoImplicit false

open OmegaCompletePartialOrder

namespace ScottDinf

noncomputable section

------------------------------------------------------------------------
-- Least elements
------------------------------------------------------------------------

/-- The embedding preserves the least element. -/
theorem emb_botD (n : ℕ) : emb n (botD n) = botD (n + 1) := by
  induction n with
  | zero => rfl
  | succ n ih =>
      refine toFn_ext ?_
      intro x
      rw [emb_succ_apply, toFn_botD, ih, toFn_botD]

/-- The embedding of a level into the limit sends the least element to the least element. -/
theorem psi_botD (n : ℕ) : psiFun n (botD n) = Dinf.botDinf :=
  le_antisymm (psi_le_iff.mpr (le_refl _)) (Dinf.botDinf_le _)

theorem ωSup_const_botDinf (c : Chain Dinf) (h : ∀ i, c i = Dinf.botDinf) :
    ωSup c = Dinf.botDinf :=
  le_antisymm (ωSup_le _ _ fun i => le_of_eq (h i)) (Dinf.botDinf_le _)

------------------------------------------------------------------------
-- The denotation of `Ω`
------------------------------------------------------------------------

/-- Self-application, as a continuous map. -/
def selfApp : Dinf →𝒄 Dinf :=
  ContinuousHom.ofFun (fun X : Dinf => Phi X X)
    (ContinuousHom.ωScottContinuous_apply Phi_continuous ωScottContinuous.id)

@[simp] theorem selfApp_apply (X : Dinf) : selfApp X = Phi X X := rfl

/-- The interpretation of `λx. x x`. -/
def deltaD : Dinf := Psi selfApp

/-- The levels of `⟦λx. x x⟧`: at level `n+1` it is `z ↦ (emb n z) z`. -/
theorem deltaD_app_succ (n : ℕ) (z : D n) :
    toFn (deltaD.app (n + 1)) z = toFn (emb n z) z := by
  have hpsi : (psiFun n z).app (n + 1) = emb n z := by
    rw [psiFun_app, psiSeq_of_gt z (by omega), psiSeq_self]
  rw [deltaD, Psi_app, PsiSeq_succ]
  change (Phi (psiFun n z) (psiFun n z)).app n = _
  rw [Phi_app_psi, hpsi]

theorem deltaD_app_zero : deltaD.app 0 = botD 0 := by
  have h := deltaD.coherent 0
  rw [← h, prj_zero_apply, deltaD_app_succ 0 (botD 0), emb_zero_apply]

/-- The heart of the computation: the self-application of `⟦λx. x x⟧` is the least element at
every level. -/
theorem deltaD_selfapp_bot : ∀ n : ℕ, toFn (deltaD.app (n + 1)) (deltaD.app n) = botD n := by
  intro n
  induction n with
  | zero =>
      rw [deltaD_app_succ 0 (deltaD.app 0), emb_zero_apply, deltaD_app_zero]
  | succ n ih =>
      rw [deltaD_app_succ (n + 1) (deltaD.app (n + 1)), emb_succ_apply, deltaD.coherent n, ih,
        emb_botD]

/-- **`Ω` denotes the least element of `D∞`.** -/
theorem ddenot_omega (ρ : DEnv) : ddenot Lambda.omega ρ = Dinf.botDinf := by
  have hdelta : ddenot (Lambda.lam (Lambda.app (Lambda.var 0) (Lambda.var 0))) ρ = deltaD := by
    rw [ddenot_lam]
    have hcont : ωScottContinuous (fun X : Dinf => Phi X X) :=
      ContinuousHom.ωScottContinuous_apply Phi_continuous ωScottContinuous.id
    have hfun : (fun X : Dinf => ddenot (Lambda.app (Lambda.var 0) (Lambda.var 0)) (dcons X ρ))
        = fun X : Dinf => Phi X X := rfl
    rw [hfun, dlamAny_eq hcont]
    rfl
  rw [Lambda.omega, ddenot_app, hdelta, Phi_apply]
  refine ωSup_const_botDinf _ fun i => ?_
  change psiFun i (toFn (deltaD.app (i + 1)) (deltaD.app i)) = Dinf.botDinf
  rw [deltaD_selfapp_bot i, psi_botD]

/-- The least element acts as the everywhere-undefined function. -/
theorem Phi_botDinf (y : Dinf) : Phi Dinf.botDinf y = Dinf.botDinf := by
  rw [Phi_apply]
  refine ωSup_const_botDinf _ fun i => ?_
  change psiFun i (toFn (Dinf.botDinf.app (i + 1)) (y.app i)) = Dinf.botDinf
  rw [Dinf.botDinf_app, toFn_botD, psi_botD]

/-- The identity denotes something other than the least element. -/
theorem ddenot_I_ne_bot (ρ : DEnv) : ddenot Lambda.I ρ ≠ Dinf.botDinf := by
  have hI : ddenot Lambda.I ρ = Psi ContinuousHom.id := by
    rw [Lambda.I, ddenot_lam]
    have hcont : ωScottContinuous (fun X : Dinf => X) := ωScottContinuous.id
    have hfun : (fun X : Dinf => ddenot (Lambda.var 0) (dcons X ρ)) = fun X : Dinf => X := rfl
    rw [hfun, dlamAny_eq hcont]
    rfl
  intro hbot
  rw [hI] at hbot
  have hid : (ContinuousHom.id : Dinf →𝒄 Dinf) = Phi Dinf.botDinf := by
    rw [← hbot, Phi_Psi]
  obtain ⟨x, y, hxy⟩ := dinf_nontrivial
  refine hxy ?_
  have hx : x = Dinf.botDinf := by
    simpa [Phi_botDinf] using congrArg (fun f : Dinf →𝒄 Dinf => f x) hid
  have hy : y = Dinf.botDinf := by
    simpa [Phi_botDinf] using congrArg (fun f : Dinf →𝒄 Dinf => f y) hid
  rw [hx, hy]

------------------------------------------------------------------------
-- Consistency of the lambda-eta calculus
------------------------------------------------------------------------

/-- Conversion in the lambda-eta calculus: the compatible equivalence relation generated by
beta reduction and eta contraction. -/
inductive ConvBE : Lambda → Lambda → Prop
  | beta {t t' : Lambda} : Lambda.step t t' → ConvBE t t'
  | eta (t : Lambda) :
      ConvBE (Lambda.lam (Lambda.app (Lambda.lift 1 0 t) (Lambda.var 0))) t
  | refl (t : Lambda) : ConvBE t t
  | symm {s t : Lambda} : ConvBE s t → ConvBE t s
  | trans {s t u : Lambda} : ConvBE s t → ConvBE t u → ConvBE s u
  | appLeft {s s' : Lambda} (t : Lambda) : ConvBE s s' → ConvBE (Lambda.app s t) (Lambda.app s' t)
  | appRight (s : Lambda) {t t' : Lambda} : ConvBE t t' → ConvBE (Lambda.app s t) (Lambda.app s t')
  | lam {t t' : Lambda} : ConvBE t t' → ConvBE (Lambda.lam t) (Lambda.lam t')

/-- **Soundness of `D∞` for the lambda-eta calculus.** -/
theorem ddenot_convBE {s t : Lambda} (h : ConvBE s t) : ∀ ρ : DEnv, ddenot s ρ = ddenot t ρ := by
  induction h with
  | beta hst => exact fun ρ => ddenot_step hst ρ
  | eta t => exact fun ρ => ddenot_eta t ρ
  | refl t => exact fun _ => rfl
  | symm _ ih => exact fun ρ => (ih ρ).symm
  | trans _ _ ih₁ ih₂ => exact fun ρ => (ih₁ ρ).trans (ih₂ ρ)
  | appLeft t _ ih => exact fun ρ => by rw [ddenot_app, ddenot_app, ih ρ]
  | appRight s _ ih => exact fun ρ => by rw [ddenot_app, ddenot_app, ih ρ]
  | lam _ ih =>
      intro ρ
      rw [ddenot_lam, ddenot_lam]
      exact dlamAny_congr fun X => ih (dcons X ρ)

/-- **The lambda-eta calculus is consistent**: `Ω` and `I` are not `βη`-convertible. -/
theorem not_convBE_omega_I : ¬ ConvBE Lambda.omega Lambda.I := by
  intro h
  have h0 := ddenot_convBE h (fun _ => Dinf.botDinf)
  rw [ddenot_omega] at h0
  exact ddenot_I_ne_bot (fun _ => Dinf.botDinf) h0.symm

theorem convBE_consistent : ∃ s t : Lambda, ¬ ConvBE s t :=
  ⟨Lambda.omega, Lambda.I, not_convBE_omega_I⟩

end

end ScottDinf
